import { SystemConfig } from './types';

export const SYSTEM_MAP: Record<string, SystemConfig> = {
  cover_letter_eb1a: {
    name: 'Cover Letter EB-1A',
    symlinkDir: 'cover-letter-eb1a',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 80000,
    multiAgent: false,
  },
  cover_letter_eb2_niw: {
    name: 'Cover Letter EB-2 NIW',
    symlinkDir: 'cover-letter-eb2-niw',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 80000,
    multiAgent: false,
  },
  cover_letter_o1: {
    name: 'Cover Letter O-1',
    symlinkDir: 'cover-letter-eb1a',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 80000,
    multiAgent: false,
  },
  resume: {
    name: 'Resume EB-1A',
    symlinkDir: 'resume-eb1a',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 40000,
    multiAgent: false,
  },
  business_plan: {
    name: 'Business Plan',
    symlinkDir: 'business-plan',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'docx',
    estimatedTokens: 200000,
    multiAgent: false,
    sequentialPrompts: 6,
  },
  methodology: {
    name: 'Metodologia',
    symlinkDir: 'metodologia',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'pptx',
    estimatedTokens: 60000,
    multiAgent: false,
  },
  declaration_of_intentions: {
    name: 'Declaracao de Intencoes',
    symlinkDir: 'declaracao-intencoes',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'pptx',
    estimatedTokens: 50000,
    multiAgent: false,
  },
  anteprojeto: {
    name: 'Case Compass',
    symlinkDir: 'estrategia-eb2',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'docx',
    estimatedTokens: 200000,
    multiAgent: false,
    sequentialPrompts: 9,
  },
  location_analysis: {
    name: 'Analise de Localizacao',
    symlinkDir: 'localizacao',
    preferredModel: 'gemini-deep-research',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'docx',
    estimatedTokens: 100000,
    multiAgent: false,
  },
  impacto_report: {
    name: 'IMPACTO',
    symlinkDir: 'impacto',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'docx',
    estimatedTokens: 200000,
    multiAgent: true,
  },
  satellite_letter_eb1: {
    name: 'Cartas Satelite EB-1A',
    symlinkDir: 'satellite-letters-eb1',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 40000,
    multiAgent: false,
    heterogeneity: true,
  },
  satellite_letter_eb2: {
    name: 'Cartas Satelite EB-2 NIW',
    symlinkDir: 'satellite-letters-eb2',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 30000,
    multiAgent: false,
    heterogeneity: true,
  },
  strategy_eb1: {
    name: 'Estrategia EB-1A',
    symlinkDir: 'estrategia-eb1',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 100000,
    multiAgent: false,
  },
  strategy_eb2: {
    name: 'Estrategia EB-2 NIW',
    symlinkDir: 'estrategia-eb2',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 100000,
    multiAgent: false,
  },
  saas_evidence: {
    name: 'SaaS Evidence Architect',
    symlinkDir: 'saas-evidence',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'md',
    estimatedTokens: 80000,
    multiAgent: false,
  },
  endeavor_assessment: {
    name: 'Avaliação de Endeavor',
    symlinkDir: '',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: true,
    outputFormat: 'md',
    estimatedTokens: 50000,
    multiAgent: false,
  },
  rfe_response: {
    name: 'Resposta a RFE',
    symlinkDir: 'cover-letter-eb1a',
    preferredModel: 'claude-opus-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 150000,
    multiAgent: false,
  },
  resume_eb2_niw: {
    name: 'Résumé EB-2 NIW',
    symlinkDir: 'resume-eb2-niw',
    preferredModel: 'claude-sonnet-4',
    requiresProfile: true,
    requiresDeepResearch: false,
    outputFormat: 'docx',
    estimatedTokens: 40000,
    multiAgent: false,
  },
};

export function getSystemForDocType(docType: string): SystemConfig {
  const system = SYSTEM_MAP[docType];
  if (!system)
    throw new Error(`Sistema nao encontrado para doc_type: ${docType}`);
  return system;
}
