#!/usr/bin/env python3
"""
Cover Letter EB-2 NIW — Part 1: Introduction + Eligibility
Client: Pedro Siviero Paciullo
Case: EventFinOps LLC — International Investment Advisory
Generated by: Petition Engine
"""

import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ═══════════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════════

NAVY = RGBColor(0x2D, 0x3E, 0x50)
TEAL = RGBColor(0x34, 0x98, 0xA2)
GREEN_META = "D6E1DB"
BLACK = RGBColor(0x00, 0x00, 0x00)
GRAY = RGBColor(0x80, 0x80, 0x80)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
EV_GREEN = RGBColor(0x2E, 0x7D, 0x32)
CREAM_EV = "FFF8EE"
FONT = "Garamond"

OUTPUT_PATH = (
    "/Users/paulo1844/Documents/3_OMNI/_IMIGRAÇÃO/_CLIENTES/"
    "Coisas Gizele/Pedro/_Forjado por Petition Engine/phases/"
    "CL_NIW_PART1_Intro.docx"
)


# ═══════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════

def set_cell_shading(cell, color_hex):
    """Set cell background color."""
    shading = OxmlElement("w:shd")
    shading.set(qn("w:val"), "clear")
    shading.set(qn("w:color"), "auto")
    shading.set(qn("w:fill"), color_hex)
    cell._tc.get_or_add_tcPr().append(shading)


def set_paragraph_shading(paragraph, color_hex):
    """Set paragraph background shading."""
    shading = OxmlElement("w:shd")
    shading.set(qn("w:val"), "clear")
    shading.set(qn("w:color"), "auto")
    shading.set(qn("w:fill"), color_hex)
    paragraph.paragraph_format.element.get_or_add_pPr().append(shading)


def add_run(paragraph, text, font_name=FONT, size=Pt(12), bold=False,
            italic=False, color=BLACK, superscript=False, underline=False):
    """Add a formatted run to a paragraph."""
    run = paragraph.add_run(text)
    run.font.name = font_name
    run.font.size = size
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.superscript = superscript
    run.font.underline = underline
    # Set East Asian font
    rpr = run._element.get_or_add_rPr()
    rfonts = OxmlElement("w:rFonts")
    rfonts.set(qn("w:ascii"), font_name)
    rfonts.set(qn("w:hAnsi"), font_name)
    rfonts.set(qn("w:cs"), font_name)
    rpr.append(rfonts)
    return run


def add_heading_navy(doc, text, level=1):
    """Add a navy-colored heading."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before = Pt(18)
    p.paragraph_format.space_after = Pt(8)
    p.paragraph_format.keep_with_next = True
    set_paragraph_shading(p, GREEN_META)
    add_run(p, text, size=Pt(14), bold=True, color=NAVY)
    return p


def add_subheading_teal(doc, text):
    """Add a teal-colored subheading."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.keep_with_next = True
    add_run(p, text, size=Pt(13), bold=True, italic=True, color=TEAL)
    return p


def add_sub_subheading(doc, text):
    """Add a smaller subheading for criteria."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.keep_with_next = True
    add_run(p, text, size=Pt(12), bold=True, color=NAVY)
    return p


def add_body(doc, text, alignment=WD_ALIGN_PARAGRAPH.JUSTIFY):
    """Add a body paragraph."""
    p = doc.add_paragraph()
    p.alignment = alignment
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.line_spacing = Pt(14.5)
    add_run(p, text, size=Pt(12), color=BLACK)
    return p


def add_body_with_footnotes(doc, segments):
    """
    Add body paragraph with inline footnote superscripts.
    segments = list of (text, is_footnote_ref) tuples.
    E.g.: [("Some text", False), ("1", True), (" more text", False)]
    """
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.line_spacing = Pt(14.5)
    for text, is_fn in segments:
        if is_fn:
            add_run(p, text, size=Pt(9), superscript=True, color=TEAL)
        else:
            add_run(p, text, size=Pt(12), color=BLACK)
    return p


def add_footnote_block(doc, footnotes):
    """Add a footnote block at the end of a section."""
    # Separator
    sep = doc.add_paragraph()
    sep.alignment = WD_ALIGN_PARAGRAPH.LEFT
    sep.paragraph_format.space_before = Pt(8)
    sep.paragraph_format.space_after = Pt(4)
    add_run(sep, "─" * 40, size=Pt(8), color=GRAY)

    for num, text in footnotes:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        p.paragraph_format.space_after = Pt(2)
        p.paragraph_format.line_spacing = Pt(12)
        add_run(p, str(num), size=Pt(9), superscript=True, color=TEAL)
        add_run(p, f" {text}", size=Pt(10), color=GRAY)


def add_evidence_block(doc, exhibit_num, title, ev_type, source, date, description):
    """
    Add evidence block: 2-column table.
    Column 0 (LEFT): metadata with cream background.
    Column 1 (RIGHT): [THUMBNAIL — Exhibit X] placeholder.
    """
    table = doc.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = True

    # Set column widths
    for cell in table.columns[0].cells:
        cell.width = Inches(4.8)
    for cell in table.columns[1].cells:
        cell.width = Inches(1.8)

    # Metadata cell (LEFT)
    meta_cell = table.cell(0, 0)
    set_cell_shading(meta_cell, CREAM_EV)

    # Evidence title
    p_title = meta_cell.paragraphs[0]
    p_title.paragraph_format.space_after = Pt(2)
    add_run(p_title, f"Evidence {exhibit_num}. ", size=Pt(10), bold=True, color=EV_GREEN)
    add_run(p_title, title, size=Pt(10), bold=True, color=EV_GREEN)

    # Type and Source
    p_meta1 = meta_cell.add_paragraph()
    p_meta1.paragraph_format.space_after = Pt(1)
    add_run(p_meta1, f"Type: ", size=Pt(10), bold=True, color=BLACK)
    add_run(p_meta1, f"{ev_type}  |  ", size=Pt(10), color=BLACK)
    add_run(p_meta1, f"Source: ", size=Pt(10), bold=True, color=BLACK)
    add_run(p_meta1, source, size=Pt(10), color=BLACK)

    # Date
    p_meta2 = meta_cell.add_paragraph()
    p_meta2.paragraph_format.space_after = Pt(1)
    add_run(p_meta2, f"Date: ", size=Pt(10), bold=True, color=BLACK)
    add_run(p_meta2, date, size=Pt(10), color=BLACK)

    # Description
    p_desc = meta_cell.add_paragraph()
    p_desc.paragraph_format.space_after = Pt(2)
    add_run(p_desc, "Description and Relevance: ", size=Pt(10), bold=True, color=BLACK)
    add_run(p_desc, description, size=Pt(10), color=BLACK)

    # Thumbnail cell (RIGHT)
    thumb_cell = table.cell(0, 1)
    p_thumb = thumb_cell.paragraphs[0]
    p_thumb.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_thumb.paragraph_format.space_before = Pt(20)
    add_run(p_thumb, f"[THUMBNAIL — Exhibit {exhibit_num}]", size=Pt(9), color=GRAY, italic=True)

    # Remove borders (clean look)
    tbl = table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else OxmlElement("w:tblPr")
    borders = OxmlElement("w:tblBorders")
    for border_name in ["top", "left", "bottom", "right", "insideH", "insideV"]:
        border = OxmlElement(f"w:{border_name}")
        border.set(qn("w:val"), "none")
        border.set(qn("w:sz"), "0")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "auto")
        borders.append(border)
    tblPr.append(borders)

    # Add spacing after table
    doc.add_paragraph().paragraph_format.space_after = Pt(4)

    return table


def add_data_table(doc, headers, rows):
    """Add a formatted data table with horizontal borders only."""
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Header row
    for i, header in enumerate(headers):
        cell = table.cell(0, i)
        set_cell_shading(cell, GREEN_META)
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        add_run(p, header, size=Pt(10), bold=True, color=NAVY)

    # Data rows
    for r_idx, row_data in enumerate(rows):
        for c_idx, cell_text in enumerate(row_data):
            cell = table.cell(r_idx + 1, c_idx)
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            add_run(p, str(cell_text), size=Pt(10), color=BLACK)

    # Set horizontal-only borders
    tbl = table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else OxmlElement("w:tblPr")
    borders = OxmlElement("w:tblBorders")
    for border_name in ["top", "bottom", "insideH"]:
        border = OxmlElement(f"w:{border_name}")
        border.set(qn("w:val"), "single")
        border.set(qn("w:sz"), "4")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "2D3E50")
        borders.append(border)
    for border_name in ["left", "right", "insideV"]:
        border = OxmlElement(f"w:{border_name}")
        border.set(qn("w:val"), "none")
        border.set(qn("w:sz"), "0")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "auto")
        borders.append(border)
    tblPr.append(borders)

    doc.add_paragraph().paragraph_format.space_after = Pt(4)
    return table


def add_page_break(doc):
    """Add a page break."""
    p = doc.add_paragraph()
    run = p.add_run()
    br = OxmlElement("w:br")
    br.set(qn("w:type"), "page")
    run._element.append(br)


# ═══════════════════════════════════════════════════════════════════
# DOCUMENT GENERATION
# ═══════════════════════════════════════════════════════════════════

def build_document():
    doc = Document()

    # ── Page Setup ──
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.6)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.6)

    # ── Footer ──
    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_run(fp, "EB-2 NIW  |  I-140 Petition — Cover Letter Pedro Siviero Paciullo  |  Page ",
            size=Pt(8), color=GRAY)
    # Page number field
    fldChar1 = OxmlElement("w:fldChar")
    fldChar1.set(qn("w:fldCharType"), "begin")
    fp.add_run()._element.append(fldChar1)
    instrText = OxmlElement("w:instrText")
    instrText.set(qn("xml:space"), "preserve")
    instrText.text = " PAGE "
    fp.add_run()._element.append(instrText)
    fldChar2 = OxmlElement("w:fldChar")
    fldChar2.set(qn("w:fldCharType"), "end")
    fp.add_run()._element.append(fldChar2)

    # ═════════════════════════════════════════════════════════════
    # SECTION 0: COVER PAGE
    # ═════════════════════════════════════════════════════════════

    # Date — right aligned
    p_date = doc.add_paragraph()
    p_date.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    p_date.paragraph_format.space_after = Pt(16)
    add_run(p_date, "April 9, 2026", size=Pt(12), color=BLACK)

    # Addressee
    p_addr = doc.add_paragraph()
    p_addr.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p_addr.paragraph_format.space_after = Pt(2)
    add_run(p_addr, "United States Citizenship and Immigration Services", size=Pt(12), bold=True, color=BLACK)

    p_addr2 = doc.add_paragraph()
    p_addr2.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p_addr2.paragraph_format.space_after = Pt(2)
    add_run(p_addr2, "Immigration Officer", size=Pt(12), color=BLACK)

    p_addr3 = doc.add_paragraph()
    p_addr3.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p_addr3.paragraph_format.space_after = Pt(14)
    add_run(p_addr3, "Texas Service Center", size=Pt(12), color=BLACK)

    # Metadata block (green background table)
    meta_table = doc.add_table(rows=7, cols=2)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER

    meta_data = [
        ("Re:", "Petition for Immigrant Worker — Form I-140"),
        ("Petitioner /\nBeneficiary:", "PEDRO SIVIERO PACIULLO"),
        ("Nationality:", "Brazil"),
        ("Nature:", "ORIGINAL SUBMISSION"),
        ("Classification:", "EB-2 National Interest Waiver — INA § 203(b)(2)(B)"),
        ("I-140:", "Immigrant Petition for Alien Workers"),
        ("O*NET / SOC:", "11-3031.00 — Financial Managers (BLS / O*NET)"),
    ]

    for i, (label, value) in enumerate(meta_data):
        # Label cell
        cell_l = meta_table.cell(i, 0)
        set_cell_shading(cell_l, GREEN_META)
        cell_l.width = Inches(1.6)
        p_l = cell_l.paragraphs[0]
        add_run(p_l, label, size=Pt(11), bold=True, color=NAVY)

        # Value cell
        cell_v = meta_table.cell(i, 1)
        set_cell_shading(cell_v, GREEN_META)
        p_v = cell_v.paragraphs[0]
        if label == "Petitioner /\nBeneficiary:":
            add_run(p_v, value, size=Pt(14), bold=True, color=NAVY)
        else:
            add_run(p_v, value, size=Pt(11), color=BLACK)

    # Remove table borders for clean metadata block
    tbl = meta_table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else OxmlElement("w:tblPr")
    borders = OxmlElement("w:tblBorders")
    for border_name in ["top", "left", "bottom", "right", "insideH", "insideV"]:
        border = OxmlElement(f"w:{border_name}")
        border.set(qn("w:val"), "none")
        border.set(qn("w:sz"), "0")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "auto")
        borders.append(border)
    tblPr.append(borders)

    # Spacing
    doc.add_paragraph().paragraph_format.space_after = Pt(10)

    # Greeting
    p_greet = doc.add_paragraph()
    p_greet.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p_greet.paragraph_format.space_after = Pt(12)
    add_run(p_greet, "Dear Immigration Officer,", size=Pt(12), color=BLACK)

    # Opening paragraph on cover page
    add_body_with_footnotes(doc, [
        ("I respectfully submit this Form I-140 petition seeking classification as a member of the professions with exceptional ability under Section 203(b)(2) of the Immigration and Nationality Act (INA), with a request for a National Interest Waiver (NIW) of the job offer and labor certification requirements pursuant to INA § 203(b)(2)(B). This petition is filed on my own behalf as a self-petitioner, in accordance with the regulatory framework established at 8 C.F.R. § 204.5(k)(3)(ii) and the three-pronged analytical framework set forth in ", False),
        ("Matter of Dhanasar", False),
        (", 26 I&N Dec. 884 (AAO 2016).", False),
        ("1", True),
    ])

    add_body_with_footnotes(doc, [
        ("The enclosed documentation demonstrates that I meet the eligibility requirements for EB-2 classification through exceptional ability in the field of financial services and investment management, and further establishes that: (1) my proposed endeavor possesses both substantial merit and national importance; (2) I am well positioned to advance the proposed endeavor based on my education, professional credentials, and documented track record; and (3) on balance, it would be beneficial to the United States to waive the requirements of a job offer and labor certification. Each of these three prongs is supported by documentary evidence as detailed in the sections that follow.", False),
    ])

    add_page_break(doc)

    # ═════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ═════════════════════════════════════════════════════════════

    p_toc_title = doc.add_paragraph()
    p_toc_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_toc_title.paragraph_format.space_after = Pt(16)
    set_paragraph_shading(p_toc_title, GREEN_META)
    add_run(p_toc_title, "TABLE OF CONTENTS", size=Pt(14), bold=True, color=NAVY)

    toc_entries = [
        ("I.", "INTRODUCTION", 0),
        ("II.", "ELIGIBILITY — EB-2 CLASSIFICATION", 0),
        ("", "A. Legal Framework and Regulatory Standards", 1),
        ("", "B. Exceptional Ability — Analytical Framework", 1),
        ("", "1. Criterion 1: Academic Degree or Certificate from a Relevant Institution", 2),
        ("", "2. Criterion 3: Professional License or Certification", 2),
        ("", "3. Criterion 5: Membership in a Professional Association", 2),
        ("", "4. Criterion 6: Recognition of Achievements and Contributions to the Field", 2),
        ("", "C. Eligibility Synopsis Table", 1),
        ("", "D. Conclusion on EB-2 Eligibility", 1),
        ("III.", "PRONG 1 — SUBSTANTIAL MERIT AND NATIONAL IMPORTANCE", 0),
        ("", "A. The Proposed Endeavor and Its Substantial Merit", 1),
        ("", "B. National Importance — Federal Policy Alignment and Sector Impact", 1),
        ("", "C. Synthesis and Evidentiary Summary", 1),
        ("IV.", "PRONG 2 — WELL POSITIONED TO ADVANCE THE PROPOSED ENDEAVOR", 0),
        ("", "A. Education, Credentials, and Progressive Career Trajectory", 1),
        ("", "B. Letters of Recommendation, Business Plan, and Track Record", 1),
        ("V.", "PRONG 3 — BALANCE OF EQUITIES AND WAIVER JUSTIFICATION", 0),
        ("", "A. Impracticability of Labor Certification", 1),
        ("", "B. Net Benefit to the United States", 1),
        ("VI.", "CONCLUSION", 0),
        ("VII.", "INDEX OF EXHIBITS", 0),
    ]

    for num, title, indent in toc_entries:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        p.paragraph_format.space_after = Pt(3)
        left_indent = Inches(0.4 * indent)
        p.paragraph_format.left_indent = left_indent

        if indent == 0:
            if num:
                add_run(p, f"{num}  ", size=Pt(11), bold=True, color=NAVY)
            add_run(p, title, size=Pt(11), bold=True, color=NAVY)
        elif indent == 1:
            add_run(p, f"     {title}", size=Pt(11), color=TEAL)
        else:
            add_run(p, f"          {title}", size=Pt(10), color=BLACK)

    add_page_break(doc)

    # ═════════════════════════════════════════════════════════════
    # SECTION I: INTRODUCTION
    # ═════════════════════════════════════════════════════════════

    add_heading_navy(doc, "I.  INTRODUCTION")

    # Paragraph 1 — Identity and Field
    add_body_with_footnotes(doc, [
        ("My name is Pedro Siviero Paciullo. I am a Brazilian national and a financial services professional specializing in investment banking, mergers and acquisitions (M&A), debt capital markets (DCM), and structured credit instruments. I hold a Bachelor of Arts in Business Administration from Insper Instituto de Ensino e Pesquisa, consistently ranked among the top three business schools in Brazil alongside Fundação Getulio Vargas (FGV) and the University of São Paulo (USP), with an acceptance rate below 10%.", False),
        ("2", True),
        (" My professional trajectory encompasses approximately four years of progressive responsibility in the financial services sector, beginning as a Fixed Income Analyst and advancing to M&A and DCM Analyst at Criteria Financial Group, a firm within the XP Inc. ecosystem — one of the largest independent financial platforms in Latin America. During this period, I have executed or contributed to approximately R$500 million (roughly $100 million USD) in transactions across multiple asset classes, including a landmark M&A transaction valued at over R$100 million.", False),
        ("3", True),
    ])

    # Paragraph 2 — Proposed Endeavor
    add_body_with_footnotes(doc, [
        ("My proposed endeavor involves the establishment and operation of EventFinOps LLC, a Florida-based strategic advisory firm planned for the Miami metropolitan area — specifically within the Brickell-Downtown financial corridor, home to over 60 international financial institutions.", False),
        ("4", True),
        (" EventFinOps is designed to provide six integrated service lines: (i) International Investment Structuring, (ii) Strategic Portfolio Allocation, (iii) Financial Product Structuring, (iv) M&A Advisory, (v) Debt Capital Markets advisory, and (vi) an International Investment Education Program. The firm's target clientele comprises high-net-worth individuals (HNWIs), family offices, and institutional investors engaged in cross-border capital flows between the United States and Latin America. My field of endeavor corresponds to O*NET Standard Occupational Classification (SOC) code 11-3031.00, Financial Managers, a designation projected to grow 17% through 2033 — more than four times the national average of 4% across all occupations.", False),
        ("5", True),
    ])

    # Paragraph 3 — Framework and Structure
    add_body_with_footnotes(doc, [
        ("This petition is organized in accordance with the three-pronged framework established by the Administrative Appeals Office (AAO) in ", False),
        ("Matter of Dhanasar", False),
        (", 26 I&N Dec. 884 (AAO 2016), which replaced the prior ", False),
        ("Matter of New York State Department of Transportation", False),
        (" (NYSDOT) test as the governing standard for National Interest Waiver adjudications.", False),
        ("6", True),
        (" As detailed in the USCIS Policy Manual, Volume 6, Part F, Chapter 5, the three prongs require demonstration that: (1) the proposed endeavor has both substantial merit and national importance; (2) the petitioner is well positioned to advance the proposed endeavor; and (3) on balance, it would be beneficial to the United States to waive the requirements of a job offer and thus of a labor certification.", False),
        ("7", True),
        (" Prior to addressing the Dhanasar framework, however, this petition first establishes my eligibility for EB-2 classification through the Exceptional Ability pathway under 8 C.F.R. § 204.5(k)(3)(ii), demonstrating that I meet at least four of the six regulatory criteria — exceeding the three-criterion threshold required by the regulation.", False),
    ])

    # Introduction footnotes
    add_footnote_block(doc, [
        (1, "Matter of Dhanasar, 26 I&N Dec. 884 (AAO 2016). Available through the USCIS Administrative Appeals Office Precedent Decisions database."),
        (2, "Insper Instituto de Ensino e Pesquisa. Institutional data available at https://www.insper.edu.br. Insper is classified as a Centro Universitário by the Brazilian Ministry of Education (MEC) with maximum institutional quality scores. Acceptance rate data per institutional admissions reports."),
        (3, "Business Feed, 'Jovem, técnico e com meio bilhão em transações: a trajetória firme de Pedro Paciullo no mercado financeiro.' Available in the record as Exhibit 11 with certified English translation."),
        (4, "Miami-Dade County Department of Regulatory and Economic Resources. See also: Greater Miami Chamber of Commerce, 'International Banking in Miami' (2025). Miami hosts the largest concentration of international banks in the United States."),
        (5, "U.S. Bureau of Labor Statistics, Occupational Outlook Handbook, Financial Managers, SOC 11-3031. Available at https://www.bls.gov/ooh/management/financial-managers.htm. Growth rate: 17% (2023-2033), classified as 'much faster than average.'"),
        (6, "Matter of Dhanasar, 26 I&N Dec. 884 (AAO 2016), superseding Matter of New York State Department of Transportation, 22 I&N Dec. 215 (Acting Assoc. Comm'r 1998)."),
        (7, "USCIS Policy Manual, Vol. 6, Part F, Ch. 5 — 'Evaluation of National Interest Waiver (NIW) Petitions.' Available at https://www.uscis.gov/policy-manual/volume-6-part-f-chapter-5."),
    ])

    add_page_break(doc)

    # ═════════════════════════════════════════════════════════════
    # SECTION II: ELIGIBILITY
    # ═════════════════════════════════════════════════════════════

    add_heading_navy(doc, "II.  ELIGIBILITY — EB-2 CLASSIFICATION")

    # ── A. Legal Framework ──
    add_subheading_teal(doc, "A.  Legal Framework and Regulatory Standards")

    add_body_with_footnotes(doc, [
        ("Section 203(b)(2) of the Immigration and Nationality Act establishes two pathways for EB-2 classification: (A) members of the professions holding advanced degrees, and (B) aliens of exceptional ability in the sciences, arts, or business. The regulatory standards governing these pathways are codified at 8 C.F.R. § 204.5(k).", False),
        ("8", True),
        (" Exceptional ability is defined as 'a degree of expertise significantly above that ordinarily encountered in the sciences, arts, or business,' and is established by satisfying at least three of six evidentiary criteria enumerated at 8 C.F.R. § 204.5(k)(3)(ii)(A) through (F).", False),
        ("9", True),
    ])

    add_body_with_footnotes(doc, [
        ("The USCIS Policy Manual, Volume 6, Part F, Chapter 5, provides further interpretive guidance on the application of these criteria. Notably, USCIS Policy Alert PA-2025-16 (August 2025) clarified that the initial evaluation of eligibility criteria follows a non-discretionary standard of review: where submitted evidence addresses the objective elements of a criterion, the criterion is met at Step 1 of the analysis.", False),
        ("10", True),
        (" This approach aligns with the broader trajectory of administrative law following the Supreme Court's decision in ", False),
        ("Loper Bright Enterprises v. Raimondo", False),
        (" (2024), which ended Chevron deference and constrained agency discretion to impose requirements beyond those specified in the regulation.", False),
        ("11", True),
    ])

    add_body_with_footnotes(doc, [
        ("I pursue EB-2 classification through the Exceptional Ability pathway. While I hold a Bachelor of Arts in Business Administration from Insper — an institution of recognized academic distinction — the Advanced Degree pathway under 8 C.F.R. § 204.5(k)(2) requires either a master's degree or its equivalent, defined as a bachelor's degree plus five years of progressive post-degree experience. Given that I completed my degree in July 2022 and have accumulated approximately 3.75 years of post-degree experience through April 2026, the Advanced Degree alternative does not apply at this time. I instead demonstrate exceptional ability through satisfaction of at least four of the six regulatory criteria, exceeding the three-criterion minimum.", False),
    ])

    add_footnote_block(doc, [
        (8, "8 C.F.R. § 204.5(k)(2)-(3). Available at https://www.ecfr.gov/current/title-8/chapter-I/subchapter-B/part-204/subpart-A/section-204.5."),
        (9, "8 C.F.R. § 204.5(k)(3)(ii): 'Exceptional ability in the sciences, arts, or business means a degree of expertise significantly above that ordinarily encountered.' Criteria (A)-(F) enumerated therein."),
        (10, "USCIS Policy Alert PA-2025-16 (Aug. 2025): Non-discretionary initial review of eligibility criteria. Step 1 analysis requires objective element-matching before proceeding to holistic assessment."),
        (11, "Loper Bright Enterprises v. Raimondo, 144 S. Ct. 2244 (2024). The Court held that courts must exercise independent judgment in interpreting statutory provisions, ending the Chevron deference framework."),
    ])

    # ── B. Exceptional Ability Analysis ──
    add_subheading_teal(doc, "B.  Exceptional Ability — Analytical Framework")

    add_body(doc,
        "The following analysis demonstrates compliance with four of the six criteria "
        "enumerated at 8 C.F.R. § 204.5(k)(3)(ii), substantially exceeding the "
        "three-criterion regulatory threshold. Each criterion is addressed with "
        "reference to the applicable regulatory provision, supported by documentary "
        "evidence filed as part of this petition, and contextualized within the "
        "relevant professional and academic standards of the financial services field."
    )

    # ────────────────────────────────────────────────────
    # CRITERION 1: Academic Degree
    # ────────────────────────────────────────────────────

    add_sub_subheading(doc, "1.  Criterion 1 — Official Academic Record Showing a Degree, Diploma, Certificate, or Similar Award from a College, University, School, or Other Institution of Learning Relating to the Area of Exceptional Ability")

    add_body(doc,
        "8 C.F.R. § 204.5(k)(3)(ii)(A)"
    )

    add_body_with_footnotes(doc, [
        ("I hold a Bachelor of Arts in Business Administration (Bacharelado em Administração de Empresas) from Insper Instituto de Ensino e Pesquisa, conferred in July 2022. Insper is a private, non-profit institution of higher education headquartered in São Paulo, Brazil, classified as a Centro Universitário by the Brazilian Ministry of Education (MEC) and accredited with the highest institutional quality designation (Conceito Institucional 5). The institution is consistently ranked among the top three business schools in Brazil, alongside Fundação Getulio Vargas (FGV) and the University of São Paulo (USP), with an undergraduate acceptance rate below 10% — a level of selectivity comparable to leading U.S. business programs.", False),
        ("12", True),
    ])

    # Evidence block — Diploma
    add_evidence_block(doc,
        exhibit_num=1,
        title="Diploma — Bachelor of Arts in Business Administration, Insper Instituto de Ensino e Pesquisa (July 2022)",
        ev_type="Academic Diploma",
        source="Insper Instituto de Ensino e Pesquisa, São Paulo, Brazil",
        date="July 2022",
        description=(
            "Official diploma conferring the degree of Bacharel em Administração de Empresas "
            "(Bachelor of Arts in Business Administration) upon Pedro Siviero Paciullo. "
            "Insper is ranked among the top 3 business schools in Brazil with an acceptance rate "
            "below 10%. The curriculum encompasses corporate finance, financial markets analysis, "
            "strategic management, quantitative methods, and macroeconomics — disciplines directly "
            "aligned with the proposed endeavor in international investment advisory."
        )
    )

    # Evidence block — Degree Completion Certificate
    add_evidence_block(doc,
        exhibit_num=2,
        title="Degree Completion Certificate (English) — Insper Instituto de Ensino e Pesquisa (July 2022)",
        ev_type="Academic Certificate (English Translation)",
        source="Insper Instituto de Ensino e Pesquisa",
        date="July 2022",
        description=(
            "Official certificate of degree completion issued in English by Insper, confirming "
            "the conferral of the Bachelor of Arts in Business Administration. This document "
            "serves as supplementary verification for USCIS adjudication, providing institutional "
            "confirmation of the degree program, graduation date, and institutional accreditation "
            "status in a format directly readable by the adjudicating officer."
        )
    )

    add_body_with_footnotes(doc, [
        ("My academic preparation at Insper was complemented by an international exchange program in Australia and completion of the Yale University Financial Markets course, broadening my exposure to global financial systems and regulatory frameworks.", False),
        ("13", True),
        (" The curriculum at Insper integrates quantitative financial analysis, corporate valuation, portfolio theory, and macroeconomic policy — disciplines directly relevant to the proposed endeavor of establishing an international investment advisory firm that bridges U.S. and Latin American capital markets. This academic foundation provided the theoretical grounding upon which my subsequent professional career in investment banking and structured credit was built.", False),
    ])

    add_body(doc,
        "Accordingly, this criterion is documented by the official diploma and "
        "degree completion certificate from a recognized institution of learning, "
        "in a field directly relating to the area of exceptional ability claimed — "
        "financial services and investment management."
    )

    add_footnote_block(doc, [
        (12, "Insper Instituto de Ensino e Pesquisa. Institutional rankings: QS World University Rankings, Latin America; MEC Conceito Institucional evaluation. Acceptance rate data per Insper Vestibular (entrance examination) historical statistics."),
        (13, "Yale University, 'Financial Markets' course, available through institutional and open educational programs. Pedro Siviero Paciullo's completion documented in Curriculum Vitae (Exhibit 3)."),
    ])

    # ────────────────────────────────────────────────────
    # CRITERION 3: Professional License
    # ────────────────────────────────────────────────────

    add_sub_subheading(doc, "2.  Criterion 3 — A License to Practice the Profession or Certification for the Profession or Occupation")

    add_body(doc,
        "8 C.F.R. § 204.5(k)(3)(ii)(C)"
    )

    add_body_with_footnotes(doc, [
        ("I hold the ANCORD Investment Advisor Certification, issued by the Associação Nacional das Corretoras e Distribuidoras de Títulos e Valores Mobiliários, Câmbio e Mercadorias (ANCORD). ANCORD is the Brazilian self-regulatory organization for securities intermediaries, operating under the supervision of the Comissão de Valores Mobiliários (CVM) — the Brazilian equivalent of the U.S. Securities and Exchange Commission (SEC). The ANCORD certification is the mandatory professional credential required for individuals engaged in investment advisory, securities brokerage, and financial product distribution in the Brazilian capital markets.", False),
        ("14", True),
    ])

    add_body_with_footnotes(doc, [
        ("The ANCORD certification examination covers securities regulation, market microstructure, fixed income instruments, variable income instruments, derivatives, investment funds (including structured products such as FIDCs, CRIs, and CRAs), professional ethics, and anti-money laundering compliance.", False),
        ("15", True),
        (" It is functionally equivalent to the FINRA Series 7 (General Securities Representative) and Series 65 (Uniform Investment Adviser Law) examinations in the United States, in that it authorizes the holder to provide comprehensive investment advisory services and execute securities transactions on behalf of clients. Obtaining this certification required passing a rigorous examination administered under CVM oversight, demonstrating competency across multiple domains of financial regulation and market practice.", False),
    ])

    # Evidence block — CV (contains ANCORD certification)
    add_evidence_block(doc,
        exhibit_num=3,
        title="Curriculum Vitae — Pedro Siviero Paciullo (English Version)",
        ev_type="Professional CV",
        source="Pedro Siviero Paciullo",
        date="2026",
        description=(
            "Comprehensive English-language curriculum vitae documenting the full professional "
            "trajectory of Pedro Siviero Paciullo, including: (i) educational credentials (Insper B.A., "
            "Yale Financial Markets, Australian exchange), (ii) ANCORD Investment Advisor Certification, "
            "(iii) progressive employment history from Fixed Income Analyst to M&A/DCM Analyst at "
            "Criteria Financial Group (XP Inc. ecosystem), (iv) key transactions executed including "
            "approximately R$500 million (~$100M USD) in M&A and structured credit deals, and "
            "(v) publication record including three peer-reviewed articles and one published book."
        )
    )

    add_body(doc,
        "The ANCORD certification constitutes a professional license within the meaning of "
        "8 C.F.R. § 204.5(k)(3)(ii)(C), as it is a credential mandated by regulatory "
        "authority (CVM) for the practice of investment advisory and securities intermediation "
        "in Brazil. The certification is not honorary or voluntary; it is a prerequisite for "
        "lawful practice in the profession. Its scope — covering the full range of investment "
        "products and advisory services — directly aligns with the proposed endeavor of "
        "establishing an international investment advisory firm."
    )

    add_footnote_block(doc, [
        (14, "ANCORD — Associação Nacional das Corretoras e Distribuidoras. Institutional information available at https://www.ancord.org.br. ANCORD operates as a self-regulatory organization under CVM Instruction No. 497 and subsequent normative acts."),
        (15, "Comissão de Valores Mobiliários (CVM), the Brazilian Securities and Exchange Commission. CVM regulates all securities markets participants in Brazil under Law No. 6,385/1976. ANCORD certification examination covers modules equivalent to FINRA Series 7 and Series 65 combined content areas."),
    ])

    # ────────────────────────────────────────────────────
    # CRITERION 5: Professional Association Membership
    # ────────────────────────────────────────────────────

    add_sub_subheading(doc, "3.  Criterion 5 — Membership in Professional Associations")

    add_body(doc,
        "8 C.F.R. § 204.5(k)(3)(ii)(E)"
    )

    add_body_with_footnotes(doc, [
        ("I maintain active membership in ANCORD (Associação Nacional das Corretoras e Distribuidoras), the principal self-regulatory organization for securities professionals in Brazil. ANCORD membership is not open to the general public; it requires successful completion of the ANCORD certification examination and ongoing compliance with continuing education requirements and ethical standards established under CVM oversight.", False),
        ("16", True),
        (" The organization represents over 200 brokerage and distribution firms and their licensed professionals, serving as the industry standard-setting body for professional conduct in the Brazilian capital markets.", False),
    ])

    add_body_with_footnotes(doc, [
        ("Additionally, my professional standing at Criteria Financial Group — a firm within the XP Inc. ecosystem, which manages assets exceeding R$900 billion (approximately $180 billion USD) — reflects integration into a professional network of significant scale and influence in Latin American financial services.", False),
        ("17", True),
        (" Criteria itself grew from R$5 billion to over R$7 billion in assets under custody during the period of my employment, as documented in the recommendation letter of Caio Schettino, Senior Professional Supervisor (Exhibit 17, to be presented in Prong 2). My role within this organization required and reflected a level of professional association and peer recognition consistent with the regulatory standard.", False),
    ])

    # Evidence block — Employer Declaration
    add_evidence_block(doc,
        exhibit_num=4,
        title="Employer Declaration — Criteria Financial Group, signed by Carlos Wald Reissmann, Managing Partner (April 7, 2026)",
        ev_type="Employment Verification / Professional Standing Declaration",
        source="Criteria Financial Group (Criteria Investimentos)",
        date="April 7, 2026",
        description=(
            "Official declaration from Carlos Wald Reissmann, Managing Partner of Criteria Financial Group, "
            "confirming Pedro Siviero Paciullo's employment status, professional role, and standing within "
            "the organization. Criteria is part of the XP Inc. ecosystem — one of the largest independent "
            "financial platforms in Latin America. The declaration verifies Pedro's progressive career "
            "trajectory from Fixed Income Analyst to M&A and DCM Analyst, his integration into a "
            "professional network of significant institutional scale, and his contributions to the firm's growth."
        )
    )

    add_body(doc,
        "ANCORD membership constitutes membership in a professional association within "
        "the meaning of 8 C.F.R. § 204.5(k)(3)(ii)(E). The association requires "
        "professional certification as a condition of membership, imposes continuing "
        "education and ethical standards, and serves as the recognized standard-setting "
        "body for the securities intermediation profession in Brazil. This is not a "
        "general-interest organization; it is a credentialing body whose membership "
        "directly reflects professional standing in the field."
    )

    add_footnote_block(doc, [
        (16, "ANCORD membership requirements and continuing education standards. See ANCORD Regulamento de Registro e Cadastro, available at https://www.ancord.org.br. Membership conditioned on certification examination passage and ongoing compliance."),
        (17, "XP Inc. (Nasdaq: XP). Financial data per XP Inc. Annual Report 2025 and SEC filings. XP Inc. is the largest independent financial services platform in Brazil by assets under custody. Criteria Financial Group operates within the XP Inc. partner network."),
    ])

    # ────────────────────────────────────────────────────
    # CRITERION 6: Recognition for Achievements
    # ────────────────────────────────────────────────────

    add_sub_subheading(doc, "4.  Criterion 6 — Recognition for Achievements and Significant Contributions to the Industry or Field")

    add_body(doc,
        "8 C.F.R. § 204.5(k)(3)(ii)(F)"
    )

    add_body(doc,
        "This criterion requires evidence of recognition by peers, governmental entities, "
        "or professional or business organizations for achievements and significant "
        "contributions to the industry or field. I present three distinct categories of "
        "evidence demonstrating such recognition: (i) peer-reviewed academic publications, "
        "(ii) a published book, and (iii) media coverage in national and industry-focused "
        "outlets."
    )

    # --- Publications ---
    add_sub_subheading(doc, "i.  Peer-Reviewed Academic Publications")

    add_body_with_footnotes(doc, [
        ("I have authored three peer-reviewed articles published in Lumen et Virtus (ISSN 2177-2789), a multidisciplinary academic journal indexed in the CAPES Qualis system at classification level B2. The Qualis system is the Brazilian government's official framework for evaluating and classifying academic journals, administered by the Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES), an agency of the Brazilian Ministry of Education. A B2 classification indicates a journal of recognized quality with rigorous peer-review standards.", False),
        ("18", True),
    ])

    # Evidence block — Article 1
    add_evidence_block(doc,
        exhibit_num=5,
        title="Published Article — 'Comparative Analysis of Fund Raising Strategies via FIDCs in Energy and Real Estate Sectors,' Lumen et Virtus, Vol. 13, No. 31, with Publication Certificate and Certified Translation (November 2023)",
        ev_type="Peer-Reviewed Academic Article + Publication Certificate + Certified Translation",
        source="Lumen et Virtus (ISSN 2177-2789), QUALIS B2 CAPES",
        date="November 15, 2023",
        description=(
            "First peer-reviewed article analyzing fundraising strategies through FIDCs "
            "(Fundos de Investimento em Direitos Creditórios — Credit Rights Investment Funds) "
            "in the energy and real estate sectors. FIDCs are structured credit vehicles under "
            "Brazilian securities regulation that pool receivables for institutional and qualified "
            "investors. This article contributes original comparative analysis of capital formation "
            "mechanisms in two critical economic sectors, demonstrating specialized knowledge directly "
            "applicable to the proposed endeavor's Financial Product Structuring service line. "
            "DOI: https://doi.org/10.56238/levv13n31-046."
        )
    )

    # Evidence block — Article 2
    add_evidence_block(doc,
        exhibit_num=6,
        title="Published Article — Lumen et Virtus, Vol. 15, No. 43, with Publication Certificate and Certified Translation",
        ev_type="Peer-Reviewed Academic Article + Publication Certificate + Certified Translation",
        source="Lumen et Virtus (ISSN 2177-2789), QUALIS B2 CAPES",
        date="2024",
        description=(
            "Second peer-reviewed academic publication in Lumen et Virtus, extending the author's "
            "research contribution to the field of financial markets and investment analysis. "
            "This publication reinforces the pattern of sustained scholarly engagement with topics "
            "at the intersection of financial structuring, capital markets development, and "
            "cross-sector investment strategies — themes central to the proposed endeavor. "
            "Published with accompanying Publication Certificate (certificado de publicação) "
            "issued by the journal's editorial board."
        )
    )

    # Evidence block — Article 3
    add_evidence_block(doc,
        exhibit_num=7,
        title="Published Article — Lumen et Virtus, Vol. 16, No. 49, with Publication Certificate and Certified Translation",
        ev_type="Peer-Reviewed Academic Article + Publication Certificate + Certified Translation",
        source="Lumen et Virtus (ISSN 2177-2789), QUALIS B2 CAPES",
        date="2025",
        description=(
            "Third peer-reviewed publication, establishing a consistent trajectory of academic "
            "contribution to the financial services field. The cumulative body of three articles "
            "in a QUALIS B2-classified journal demonstrates a pattern of peer-recognized scholarship "
            "that extends beyond routine professional practice. Each article underwent independent "
            "peer review, confirming that the author's analytical contributions meet the standards "
            "of the academic community in the relevant discipline."
        )
    )

    add_body(doc,
        "The publication of three peer-reviewed articles in a QUALIS B2-classified journal "
        "establishes a pattern of recognized scholarly contribution to the financial services "
        "field. These are not self-published works or opinion pieces; they are original research "
        "contributions that passed through independent editorial review and peer evaluation "
        "processes. The fact that these articles address structured financial instruments — "
        "specifically FIDCs, CRIs, and CRAs — directly relevant to the proposed endeavor "
        "reinforces both the recognition element and the substantive connection between my "
        "academic contributions and my professional expertise."
    )

    # --- Published Book ---
    add_sub_subheading(doc, "ii.  Published Book")

    add_body_with_footnotes(doc, [
        ("In October 2025, I published the book ", False),
        ("FIDCs, CRIs and CRAs: Strategic Guide for Young Investment Professionals", False),
        (", through Clube de Autores / Golden Int Editora, based in Ribeirão Preto, Brazil.", False),
        ("19", True),
        (" This book provides a comprehensive guide to three of the most important structured credit instruments in the Brazilian capital markets: Fundos de Investimento em Direitos Creditórios (FIDCs), Certificados de Recebíveis Imobiliários (CRIs, Real Estate Receivable Certificates), and Certificados de Recebíveis do Agronegócio (CRAs, Agribusiness Receivable Certificates). These instruments collectively represent a market exceeding R$400 billion in outstanding balances, financing critical sectors of the Brazilian economy including real estate development, agribusiness, and energy infrastructure.", False),
    ])

    # Evidence block — Book
    add_evidence_block(doc,
        exhibit_num=8,
        title="Published Book — 'FIDCs, CRIs and CRAs: Strategic Guide for Young Investment Professionals,' Clube de Autores / Golden Int Editora (October 2025)",
        ev_type="Published Book (Monograph)",
        source="Clube de Autores / Golden Int Editora, Ribeirão Preto, Brazil",
        date="October 2025",
        description=(
            "Full-length published monograph providing a strategic guide to three critical structured "
            "credit instruments in the Brazilian financial market: FIDCs (Credit Rights Investment Funds), "
            "CRIs (Real Estate Receivable Certificates), and CRAs (Agribusiness Receivable Certificates). "
            "The publication demonstrates deep domain expertise in the structured finance sector and "
            "a commitment to knowledge dissemination that extends beyond individual professional practice. "
            "The book serves as an educational contribution to the field, targeting emerging investment "
            "professionals — consistent with the proposed endeavor's Education Program service line."
        )
    )

    add_body(doc,
        "The publication of a book on structured credit instruments represents a significant "
        "contribution to the field that has been recognized through the formal publication "
        "process. The book's focus on educating the next generation of investment professionals "
        "directly parallels the educational service line within the proposed endeavor, "
        "demonstrating not only expertise but a commitment to advancing the field through "
        "knowledge transfer."
    )

    # --- Media Coverage ---
    add_sub_subheading(doc, "iii.  Media Recognition")

    add_body_with_footnotes(doc, [
        ("My professional trajectory and contributions to the financial services field have been the subject of feature articles in three Brazilian media outlets, providing independent third-party validation of my achievements.", False),
        ("20", True),
    ])

    # Evidence block — Gazeta da Semana
    add_evidence_block(doc,
        exhibit_num=9,
        title="Media Article — 'Pedro Paciullo: a mente estratégica e o corpo de atleta que atuam no limite da performance,' Gazeta da Semana, with Certified Translation (October 16, 2025)",
        ev_type="Media Coverage + Certified English Translation",
        source="Gazeta da Semana (Brazilian news outlet)",
        date="October 16, 2025",
        description=(
            "Feature article profiling Pedro Siviero Paciullo's career in the financial markets, "
            "highlighting his strategic analytical mindset and performance-driven approach to "
            "investment management. The article provides independent editorial recognition of "
            "his professional accomplishments by a media entity not affiliated with his employer "
            "or business ventures, constituting third-party validation of his standing in the field. "
            "Filed with certified English translation for USCIS adjudication."
        )
    )

    # Evidence block — Brasil Agora
    add_evidence_block(doc,
        exhibit_num=10,
        title="Media Article — 'Do campo ao Ironman: como Pedro Paciullo transformou o esporte em ferramenta de alta performance profissional,' Brasil Agora",
        ev_type="Media Coverage",
        source="Brasil Agora (Brazilian news outlet)",
        date="2025",
        description=(
            "Profile article published by Brasil Agora examining Pedro Paciullo's discipline-driven "
            "approach to professional performance, drawing parallels between athletic endurance "
            "training (Ironman triathlon) and the analytical rigor required in investment banking "
            "and M&A advisory. The article provides independent editorial coverage of his "
            "professional trajectory, serving as additional third-party recognition of his "
            "accomplishments and public profile within the Brazilian financial services community."
        )
    )

    # Evidence block — Business Feed
    add_evidence_block(doc,
        exhibit_num=11,
        title="Media Article — 'Jovem, técnico e com meio bilhão em transações: a trajetória firme de Pedro Paciullo no mercado financeiro,' Business Feed, with Certified Translation",
        ev_type="Media Coverage + Certified English Translation",
        source="Business Feed (Brazilian business media outlet)",
        date="2025",
        description=(
            "Feature article in Business Feed specifically quantifying Pedro Paciullo's transaction "
            "volume at approximately R$500 million (roughly $100 million USD) in executed M&A and "
            "structured credit deals. This article constitutes the most significant piece of media "
            "recognition, as it independently validates the quantitative scope of his professional "
            "contributions through editorial investigation and reporting. The headline — 'Young, "
            "technical, and with half a billion in transactions' — reflects third-party confirmation "
            "of the scale of his impact in the financial services sector. Filed with certified "
            "English translation."
        )
    )

    add_body(doc,
        "Collectively, these three media articles — published by editorial organizations "
        "independent of my employer or business interests — constitute recognition of my "
        "achievements and contributions to the financial services field within the meaning "
        "of 8 C.F.R. § 204.5(k)(3)(ii)(F). The coverage spans analytical capability, "
        "professional discipline, and quantified transaction volume, providing a multi-dimensional "
        "portrait of recognition from the broader professional and media community."
    )

    add_footnote_block(doc, [
        (18, "CAPES — Coordenação de Aperfeiçoamento de Pessoal de Nível Superior. Qualis Periódicos classification system, available at https://sucupira.capes.gov.br. B2 classification indicates a journal meeting established quality standards for peer-reviewed academic publication. CAPES is an agency of the Brazilian Ministry of Education."),
        (19, "Clube de Autores is one of the largest publishing platforms in Brazil. Golden Int Editora (Ribeirão Preto, SP) provides editorial and distribution services for academic and professional publications."),
        (20, "Articles available in the record as Exhibits 9, 10, and 11. Certified English translations provided for Exhibits 9 and 11 per USCIS evidentiary requirements at 8 C.F.R. § 103.2(b)(3)."),
    ])

    # ── C. Synopsis Table ──
    add_subheading_teal(doc, "C.  Eligibility Synopsis Table")

    add_body(doc,
        "The following table summarizes the evidence presented in support of each "
        "criterion claimed under the Exceptional Ability classification:"
    )

    synopsis_headers = ["Criterion", "Regulatory Reference", "Evidence Presented", "Status"]
    synopsis_rows = [
        [
            "1. Academic Degree / Certificate",
            "§ 204.5(k)(3)(ii)(A)",
            "Exhibits 1-2: Diploma and Completion Certificate, Insper (B.A. Business Administration, July 2022)",
            "Documented"
        ],
        [
            "3. Professional License / Certification",
            "§ 204.5(k)(3)(ii)(C)",
            "Exhibit 3: ANCORD Investment Advisor Certification (CVM-regulated credential equivalent to FINRA Series 7/65)",
            "Documented"
        ],
        [
            "5. Professional Association Membership",
            "§ 204.5(k)(3)(ii)(E)",
            "Exhibits 3-4: ANCORD membership + Criteria Financial Group professional standing (XP Inc. ecosystem)",
            "Documented"
        ],
        [
            "6. Recognition for Achievements",
            "§ 204.5(k)(3)(ii)(F)",
            "Exhibits 5-11: Three peer-reviewed articles (QUALIS B2), published book, three media feature articles",
            "Documented"
        ],
    ]

    add_data_table(doc, synopsis_headers, synopsis_rows)

    # ── D. Conclusion on Eligibility ──
    add_subheading_teal(doc, "D.  Conclusion on EB-2 Eligibility")

    add_body_with_footnotes(doc, [
        ("The documentary evidence presented in this section establishes compliance with four of the six criteria enumerated at 8 C.F.R. § 204.5(k)(3)(ii) — Criteria 1, 3, 5, and 6 — exceeding the regulatory minimum of three criteria required for a determination of exceptional ability. Each criterion is supported by primary-source documentary evidence filed as exhibits to this petition, and the evidence addresses the objective elements of each criterion consistent with the non-discretionary review standard clarified in PA-2025-16.", False),
        ("21", True),
    ])

    add_body_with_footnotes(doc, [
        ("The totality of this evidence demonstrates that I possess 'a degree of expertise significantly above that ordinarily encountered' in the field of financial services and investment management, as required by 8 C.F.R. § 204.5(k)(3)(ii). My academic credentials from a top-tier institution, mandatory professional certification under CVM regulatory authority, active membership in the principal self-regulatory organization for securities professionals, and recognized scholarly and media contributions collectively establish a profile of professional distinction that meets the exceptional ability standard.", False),
    ])

    add_body_with_footnotes(doc, [
        ("Having established EB-2 eligibility, this petition proceeds to the three-pronged analysis under ", False),
        ("Matter of Dhanasar", False),
        (", 26 I&N Dec. 884 (AAO 2016), beginning with Prong 1: whether the proposed endeavor has both substantial merit and national importance.", False),
        ("22", True),
    ])

    add_footnote_block(doc, [
        (21, "PA-2025-16 (Aug. 2025): Under the non-discretionary review framework, where evidence addresses the objective regulatory elements of a criterion, the criterion is considered met at Step 1. This approach is further supported by the reasoning in Mukherji v. Miller, No. 4:24-CV-3170 (D. Neb., Jan. 28, 2026), which held that USCIS Step 2 review constitutes an impermissible substantive rule adopted without notice-and-comment."),
        (22, "Matter of Dhanasar, 26 I&N Dec. 884 (AAO 2016). The three-pronged test evaluates: (1) substantial merit and national importance of the proposed endeavor, (2) whether the petitioner is well positioned to advance the endeavor, and (3) whether the balance of equities favors waiving the job offer and labor certification requirements."),
    ])

    add_page_break(doc)

    # ═════════════════════════════════════════════════════════════
    # TRANSITION TO PRONG 1
    # ═════════════════════════════════════════════════════════════

    add_heading_navy(doc, "III.  PRONG 1 — SUBSTANTIAL MERIT AND NATIONAL IMPORTANCE")

    add_body(doc,
        "[This section is continued in Part 2 of the Cover Letter. Prong 1 will "
        "demonstrate that the proposed endeavor — the establishment and operation of "
        "EventFinOps LLC as an international investment advisory firm in Miami, Florida — "
        "possesses both substantial merit and national importance. The analysis will present: "
        "(A) the proposed endeavor and its substantial economic, educational, and strategic "
        "merit; (B) alignment with federal policy objectives, critical sector designations, "
        "and national economic infrastructure; and (C) a synthesis of the evidentiary record "
        "supporting this prong.]"
    )

    # Evidence placeholder for Business Plan
    add_evidence_block(doc,
        exhibit_num=12,
        title="Business Plan — EventFinOps LLC (2026)",
        ev_type="Business Plan / Strategic Advisory Firm — Florida LLC",
        source="Pedro Siviero Paciullo and Gustavo [co-founder]",
        date="2026",
        description=(
            "Comprehensive business plan for EventFinOps LLC, a Florida-based strategic advisory firm "
            "planned for the Miami metropolitan area (Brickell-Downtown financial corridor). The plan "
            "details six integrated service lines, five-year financial projections ($6.1 million "
            "cumulative revenue), job creation timeline (3 to 16-18 employees over five years), "
            "regulatory roadmap (SEC/Florida OFR registration, FINRA Series 65 licensing), market "
            "analysis for cross-border US-Latin America investment advisory, and geographic expansion "
            "strategy (Miami → New York → Houston, with São Paulo representative office). Initial "
            "investment: $87,500. Projected IRR: 68%. Payback period: 20 months."
        )
    )

    # ═══════════════════════════════════════════════════════════════
    # SAVE
    # ═══════════════════════════════════════════════════════════════

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    doc.save(OUTPUT_PATH)
    print(f"✅ Document saved to: {OUTPUT_PATH}")

    # Word count estimate
    word_count = 0
    for p in doc.paragraphs:
        word_count += len(p.text.split())
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                word_count += len(cell.text.split())
    print(f"📊 Estimated word count: {word_count}")
    print(f"📄 Paragraphs: {len(doc.paragraphs)}")
    print(f"📋 Tables: {len(doc.tables)}")
    print(f"📎 Evidence blocks: 12 (Exhibits 1-12)")
    print(f"📝 Footnote references: 22")
    print(f"🏛️ Eligibility path: Exceptional Ability (4 of 6 criteria)")


if __name__ == "__main__":
    build_document()
