#!/usr/bin/env python3
"""
RÉSUMÉ EB-2 NIW — DENI RUBEN MOREIRA
V4 DNA Visual System — 100% Garamond + Navy/Teal palette
Generated by Petition Engine

USAGE:
    python3 generate_resume_deni.py
"""
import os
import sys
import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

# =============================================================================
# V4 DNA VISUAL CONSTANTS
# =============================================================================

NAVY = "2D3E50"
TEAL = "3498A2"
WHITE = "FFFFFF"
BLACK = "000000"
DARK_GRAY = "333333"
MED_GRAY = "666666"
LIGHT_GRAY = "F5F5F5"
BORDER_GRAY = "CCCCCC"

NAVY_RGB = RGBColor(0x2D, 0x3E, 0x50)
TEAL_RGB = RGBColor(0x34, 0x98, 0xA2)
WHITE_RGB = RGBColor(0xFF, 0xFF, 0xFF)
BLACK_RGB = RGBColor(0x00, 0x00, 0x00)
DARK_GRAY_RGB = RGBColor(0x33, 0x33, 0x33)
MED_GRAY_RGB = RGBColor(0x66, 0x66, 0x66)

FONT = "Garamond"
META_WIDTH = 5760   # dxa
THUMB_WIDTH = 4320  # dxa

# Output paths
DENI_FOLDER = "/Users/paulo1844/Documents/_PROEX (A COMPLEMENTAR)/_2. MEUS CASOS/2026/Deni Rubens (Direto)"
RESUME_FOLDER = os.path.join(DENI_FOLDER, "RÉSUMÉ")

# =============================================================================
# HELPER FUNCTIONS — V4 DNA Visual System
# =============================================================================

def set_cell_shading(cell, color):
    shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color}"/>')
    cell._tc.get_or_add_tcPr().append(shading)


def set_cell_borders(cell, color=BORDER_GRAY, sz="4"):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    borders = parse_xml(
        f'<w:tcBorders {nsdecls("w")}>'
        f'  <w:top w:val="single" w:sz="{sz}" w:space="0" w:color="{color}"/>'
        f'  <w:left w:val="single" w:sz="{sz}" w:space="0" w:color="{color}"/>'
        f'  <w:bottom w:val="single" w:sz="{sz}" w:space="0" w:color="{color}"/>'
        f'  <w:right w:val="single" w:sz="{sz}" w:space="0" w:color="{color}"/>'
        f'</w:tcBorders>'
    )
    tcPr.append(borders)


def set_cell_width(cell, width_dxa):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcW = parse_xml(f'<w:tcW {nsdecls("w")} w:w="{width_dxa}" w:type="dxa"/>')
    tcPr.append(tcW)


def set_cell_margins(cell, top=0, bottom=0, left=80, right=80):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    margins = parse_xml(
        f'<w:tcMar {nsdecls("w")}>'
        f'  <w:top w:w="{top}" w:type="dxa"/>'
        f'  <w:bottom w:w="{bottom}" w:type="dxa"/>'
        f'  <w:left w:w="{left}" w:type="dxa"/>'
        f'  <w:right w:w="{right}" w:type="dxa"/>'
        f'</w:tcMar>'
    )
    tcPr.append(margins)


def add_run(paragraph, text, font_name=FONT, size=Pt(10.5), color=BLACK_RGB,
            bold=False, italic=False):
    run = paragraph.add_run(text)
    run.font.name = font_name
    run.font.size = size
    run.font.color.rgb = color
    run.font.bold = bold
    run.font.italic = italic
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn('w:rFonts'))
    if rFonts is None:
        rFonts = parse_xml(f'<w:rFonts {nsdecls("w")} w:ascii="{font_name}" '
                           f'w:hAnsi="{font_name}" w:eastAsia="{font_name}" '
                           f'w:cs="{font_name}"/>')
        rPr.insert(0, rFonts)
    else:
        rFonts.set(qn('w:ascii'), font_name)
        rFonts.set(qn('w:hAnsi'), font_name)
        rFonts.set(qn('w:eastAsia'), font_name)
        rFonts.set(qn('w:cs'), font_name)
    return run


def add_paragraph_text(doc, text, size=Pt(10.5), color=BLACK_RGB,
                       bold=False, italic=False, alignment=WD_ALIGN_PARAGRAPH.JUSTIFY,
                       space_after=Pt(6), space_before=Pt(0)):
    p = doc.add_paragraph()
    p.alignment = alignment
    p.paragraph_format.space_after = space_after
    p.paragraph_format.space_before = space_before
    add_run(p, text, size=size, color=color, bold=bold, italic=italic)
    return p


def add_bullet(doc, text, level=0, size=Pt(10.5), color=BLACK_RGB):
    symbol = "\u25cf" if level == 0 else "\u25cb"
    indent = Inches(0.3) if level == 0 else Inches(0.6)
    font_size = size if level == 0 else Pt(10)
    text_color = color if level == 0 else DARK_GRAY_RGB

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.left_indent = indent
    p.paragraph_format.first_line_indent = Inches(-0.2)
    add_run(p, f"{symbol} ", size=font_size, color=text_color)
    add_run(p, text, size=font_size, color=text_color)
    return p


def add_navy_section_header(doc, title):
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell = table.rows[0].cells[0]
    set_cell_shading(cell, NAVY)
    set_cell_margins(cell, top=60, bottom=60, left=120, right=120)

    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    add_run(p, title.upper(), size=Pt(11), color=WHITE_RGB, bold=True)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(4)
    spacer.paragraph_format.space_after = Pt(4)
    return table


def add_teal_sub_header(doc, title):
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell = table.rows[0].cells[0]
    set_cell_shading(cell, TEAL)
    set_cell_margins(cell, top=40, bottom=40, left=120, right=120)

    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    add_run(p, title, size=Pt(10), color=WHITE_RGB, bold=True)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(2)
    spacer.paragraph_format.space_after = Pt(4)
    return table


def add_company_box(doc, company, role, period, location, website, about):
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell = table.rows[0].cells[0]
    set_cell_shading(cell, LIGHT_GRAY)
    set_cell_borders(cell, BORDER_GRAY, "4")
    set_cell_margins(cell, top=80, bottom=80, left=120, right=120)

    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_after = Pt(2)
    add_run(p, company.upper(), size=Pt(11), color=NAVY_RGB, bold=True)

    for label, val in [("Role", role), ("Period", period), ("Location", location)]:
        px = cell.add_paragraph()
        px.paragraph_format.space_after = Pt(1)
        px.paragraph_format.space_before = Pt(0)
        add_run(px, f"{label}: ", size=Pt(10), color=BLACK_RGB, bold=True)
        add_run(px, val, size=Pt(10), color=BLACK_RGB)

    if website:
        pw = cell.add_paragraph()
        pw.paragraph_format.space_after = Pt(2)
        pw.paragraph_format.space_before = Pt(0)
        add_run(pw, "Website: ", size=Pt(10), color=BLACK_RGB, bold=True)
        add_run(pw, website, size=Pt(10), color=BLACK_RGB)

    if about:
        pa = cell.add_paragraph()
        pa.paragraph_format.space_after = Pt(0)
        pa.paragraph_format.space_before = Pt(4)
        add_run(pa, about, size=Pt(9.5), color=DARK_GRAY_RGB, italic=True)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(4)
    spacer.paragraph_format.space_after = Pt(4)
    return table


def add_evidence_block(doc, metadata_pairs, impact_text, thumb_label="[Exhibit]"):
    table = doc.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    left = table.rows[0].cells[0]
    right = table.rows[0].cells[1]

    set_cell_width(left, META_WIDTH)
    set_cell_width(right, THUMB_WIDTH)
    set_cell_borders(left, BORDER_GRAY, "4")
    set_cell_borders(right, BORDER_GRAY, "4")
    set_cell_margins(left, top=60, bottom=60, left=100, right=60)
    set_cell_margins(right, top=60, bottom=60, left=60, right=100)

    first = True
    for label, value in metadata_pairs:
        p = left.paragraphs[0] if first else left.add_paragraph()
        first = False
        p.paragraph_format.space_after = Pt(2)
        p.paragraph_format.space_before = Pt(0)
        add_run(p, f"{label}: ", size=Pt(10), color=BLACK_RGB, bold=True)
        add_run(p, value, size=Pt(10), color=BLACK_RGB)

    if impact_text:
        p_label = left.add_paragraph()
        p_label.paragraph_format.space_before = Pt(6)
        p_label.paragraph_format.space_after = Pt(2)
        add_run(p_label, "Description & Impact:", size=Pt(9.5), color=NAVY_RGB, bold=True)

        p_impact = left.add_paragraph()
        p_impact.paragraph_format.space_after = Pt(2)
        p_impact.paragraph_format.space_before = Pt(0)
        add_run(p_impact, impact_text, size=Pt(9.5), color=DARK_GRAY_RGB, italic=True)

    right.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
    p_thumb = right.paragraphs[0]
    p_thumb.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_run(p_thumb, thumb_label, size=Pt(9), color=MED_GRAY_RGB, italic=True)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(4)
    spacer.paragraph_format.space_after = Pt(4)
    return table


def add_data_table(doc, headers, rows, col_widths=None):
    n_cols = len(headers)
    n_rows = len(rows) + 1
    table = doc.add_table(rows=n_rows, cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    for j, header in enumerate(headers):
        cell = table.rows[0].cells[j]
        set_cell_shading(cell, NAVY)
        set_cell_margins(cell, top=40, bottom=40, left=60, right=60)
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        add_run(p, header, size=Pt(9.5), color=WHITE_RGB, bold=True)

    for i, row_data in enumerate(rows):
        bg = LIGHT_GRAY if i % 2 == 0 else WHITE
        for j, val in enumerate(row_data):
            cell = table.rows[i + 1].cells[j]
            set_cell_shading(cell, bg)
            set_cell_margins(cell, top=30, bottom=30, left=60, right=60)
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            add_run(p, str(val), size=Pt(9.5), color=BLACK_RGB)

    if col_widths:
        for j, w in enumerate(col_widths):
            for row in table.rows:
                set_cell_width(row.cells[j], w)

    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(4)
    spacer.paragraph_format.space_after = Pt(6)
    return table


def setup_document():
    doc = Document()

    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(0)
    section.bottom_margin = Inches(0.5)
    section.left_margin = Inches(0.65)
    section.right_margin = Inches(0.65)
    section.header_distance = Inches(0)

    style = doc.styles['Normal']
    font = style.font
    font.name = FONT
    font.size = Pt(10.5)
    font.color.rgb = BLACK_RGB
    rPr = style.element.get_or_add_rPr()
    rFonts = parse_xml(f'<w:rFonts {nsdecls("w")} w:ascii="{FONT}" '
                       f'w:hAnsi="{FONT}" w:eastAsia="{FONT}" w:cs="{FONT}"/>')
    rPr.insert(0, rFonts)

    # ── HEADER (3 rows x 2 cols) ──
    header = section.header
    header.is_linked_to_previous = False
    for p in header.paragraphs:
        p.clear()

    h_table = header.add_table(rows=3, cols=2, width=Inches(8.5))
    h_table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Row 0: Navy — Name
    for cell in h_table.rows[0].cells:
        set_cell_shading(cell, NAVY)
        set_cell_margins(cell, top=80, bottom=40, left=120, right=120)
    p0 = h_table.rows[0].cells[0].paragraphs[0]
    p0.alignment = WD_ALIGN_PARAGRAPH.LEFT
    add_run(p0, "DENI RUBEN MOREIRA", size=Pt(20), color=WHITE_RGB, bold=True)
    h_table.rows[0].cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # Row 1: Navy — RÉSUMÉ | email + SOC
    for cell in h_table.rows[1].cells:
        set_cell_shading(cell, NAVY)
        set_cell_margins(cell, top=20, bottom=40, left=120, right=120)

    p1_left = h_table.rows[1].cells[0].paragraphs[0]
    p1_left.alignment = WD_ALIGN_PARAGRAPH.LEFT
    add_run(p1_left, "R\u00c9SUM\u00c9", size=Pt(11), color=WHITE_RGB, bold=True)
    add_run(p1_left, "          SOC/O*Net: 15-1299.09 | EB-2 NIW",
            size=Pt(9), color=WHITE_RGB)

    p1_right = h_table.rows[1].cells[1].paragraphs[0]
    p1_right.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    add_run(p1_right, "deni.ruben@gmail.com", size=Pt(9), color=WHITE_RGB)

    # Row 2: Teal accent line
    for cell in h_table.rows[2].cells:
        set_cell_shading(cell, TEAL)
        set_cell_margins(cell, top=4, bottom=4, left=0, right=0)
    h_table.rows[2].cells[0].paragraphs[0].paragraph_format.space_before = Pt(0)
    h_table.rows[2].cells[0].paragraphs[0].paragraph_format.space_after = Pt(0)
    h_table.rows[2].cells[1].paragraphs[0].paragraph_format.space_before = Pt(0)
    h_table.rows[2].cells[1].paragraphs[0].paragraph_format.space_after = Pt(0)

    # ── FOOTER (Navy bar with page number) ──
    footer = section.footer
    footer.is_linked_to_previous = False
    for p in footer.paragraphs:
        p.clear()

    f_table = footer.add_table(rows=1, cols=1, width=Inches(8.5))
    f_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    f_cell = f_table.rows[0].cells[0]
    set_cell_shading(f_cell, NAVY)
    set_cell_margins(f_cell, top=40, bottom=40, left=120, right=120)

    f_para = f_cell.paragraphs[0]
    f_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_run(f_para, "R\u00e9sum\u00e9 Deni Ruben Moreira \u2014 EB-2 NIW \u2014 Page ",
            size=Pt(9), color=WHITE_RGB)

    fld_char1 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="begin"/>')
    run_page = f_para.add_run()
    run_page._element.append(fld_char1)
    instr = parse_xml(f'<w:instrText {nsdecls("w")} xml:space="preserve"> PAGE </w:instrText>')
    run_page2 = f_para.add_run()
    run_page2._element.append(instr)
    run_page2.font.name = FONT
    run_page2.font.size = Pt(9)
    run_page2.font.color.rgb = WHITE_RGB
    fld_char2 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="end"/>')
    run_page3 = f_para.add_run()
    run_page3._element.append(fld_char2)

    return doc


# =============================================================================
# SECTION BUILDERS
# =============================================================================

def build_summary(doc):
    add_navy_section_header(doc, "SUMMARY OF PROFESSIONAL QUALIFICATIONS")

    add_paragraph_text(doc,
        "Deni Ruben Moreira is a seasoned technology management professional with over 15 years "
        "of progressive experience spanning enterprise resource planning (ERP), business intelligence (BI), "
        "process automation, IT governance, regulatory compliance, and workforce training across multiple "
        "industries and geographies. His career, built across nine organizations in Brazil and Canada, "
        "reflects a deliberate trajectory from financial systems analysis to integrated digital "
        "transformation leadership for small and medium enterprises (SMEs)."
    )

    bullets = [
        "Over 15 years of continuous professional experience in IT project management, ERP implementation, "
        "business intelligence, and digital transformation, accumulated across nine organizations in two "
        "countries (Brazil and Canada) and five industry sectors (Exhibit 29).",

        "Holds a Bachelor of Business Administration from Universidade Anhembi Morumbi (Brazil, 2009) and "
        "a Business Analyst of Information Technology diploma from Montreal College of Information Technology "
        "(Canada, 2020). Combined credentials evaluated by GEO Credential Services as equivalent to a "
        "Master of Science in Project Management in the United States (Exhibit 3).",

        "Certified Project Management Professional (PMP, #3770976) by the Project Management Institute, "
        "valid through February 2027 (Exhibit 24). Certified SAP S/4HANA for Management Accounting "
        "Associates by SAP (Exhibit 22). Holds PMI Disciplined Agile Scrum Master (DASM) credential "
        "(Exhibit 23).",

        "Elevated to IEEE Senior Member in February 2026 (Member #101975995), a distinction reserved "
        "for professionals with at least 10 years of significant practice and demonstrating outstanding "
        "contributions in the field of technology. Only approximately 10% of IEEE members hold this "
        "grade (Exhibits 5\u20137).",

        "Published author of three peer-reviewed articles in international journals on ERP implementation "
        "strategies, digital transformation for SMEs, and AI-enhanced enterprise systems (Exhibits 11\u201313). "
        "Invited peer reviewer for SAMRIDDHI \u2014 A Journal of Management & Research, completing two "
        "manuscript evaluations in December 2025 (Exhibits 14\u201317).",

        "Managed and coordinated enterprise technology projects with combined budgets exceeding "
        "USD 160 million, including a USD 75 million SAP/ERP corporate implementation across 30+ locations "
        "in Canada and the United States serving 8,000+ end users at Resolute Forest Products (Exhibit 29).",

        "Successfully led the end-to-end implementation of Microsoft Business Central 365 SaaS for "
        "Souris Mini, a Canadian retail company, training 50+ users, processing 10,000+ monthly transactions, "
        "and reducing financial reporting cycle time from 10 business days to 5 business days (Exhibit 2).",

        "Directed over 10 Microsoft Business Central ERP implementations for small and medium enterprises "
        "in Canada through Nexus Innovation, improving average operational efficiency by 25% and reducing "
        "project delivery timelines by 30% (Exhibit 29).",

        "Oversaw a USD 50 million annual IT budget at PSP Investments, one of Canada\u2019s largest pension "
        "fund managers (CAD 243.7 billion in net assets), implementing cost monitoring systems that "
        "reduced budget overrun incidents by 20% (Exhibit 29).",

        "Trilingual professional \u2014 fluent in English, French, and Portuguese \u2014 enabling effective "
        "stakeholder management in multicultural and multinational environments across North America, "
        "South America, and Europe.",

        "Founder of DRM Solutions LLC (Dallas-Fort Worth, Texas), a consulting firm focused on integrated "
        "digital transformation solutions for American SMEs, combining ERP implementation, business "
        "intelligence, regulatory compliance, process automation, and workforce training (Exhibit 30).",
    ]
    for b in bullets:
        add_bullet(doc, b)


def build_tools(doc):
    add_navy_section_header(doc, "TOOLS & SOFTWARE PROFICIENCY")

    add_paragraph_text(doc,
        "This section highlights the technical tools and platforms actively used throughout "
        "Deni Ruben Moreira\u2019s professional career, demonstrating hands-on proficiency directly "
        "relevant to integrated digital transformation consulting for small and medium enterprises "
        "in the United States."
    )

    categories = [
        ("Enterprise Resource Planning (ERP) Systems", [
            ("SAP S/4HANA and SAP ECC",
             "Advanced proficiency in SAP FI, CO, Management Accounting, MM, and BPC. Applied across "
             "enterprise-scale implementations at Resolute Forest Products (8,000+ users, 30+ locations), "
             "Allergan, and PSP Investments. Certified SAP S/4HANA for Management Accounting (Exhibit 22)."),
            ("SAP Business One",
             "Proficiency in configuring and deploying SAP Business One for SMEs, supporting financial "
             "management, inventory control, and operational reporting at Nexus Innovation."),
            ("Microsoft Dynamics 365 Business Central",
             "End-to-end implementation proficiency including financial management, supply chain, sales, "
             "and reporting. Led 10+ implementations for Canadian SMEs at Nexus Innovation and Souris Mini (Exhibit 2)."),
        ]),
        ("Business Intelligence & Data Analytics", [
            ("Microsoft Power BI",
             "Dashboards, KPI scorecards, and automated reporting for executive decision-making. Applied at "
             "PSP Investments, CGI, and Addmore Group."),
            ("SAP BPC",
             "Automated financial consolidation across 30+ locations and 5 currencies at Resolute Forest Products, "
             "reducing month-end closing from 15 days to 6 days."),
            ("Microsoft Excel (Advanced) and Power Query",
             "Financial modeling, pivot tables, VLOOKUP/INDEX-MATCH, and Power Query for ETL operations."),
        ]),
        ("Project Management & Governance", [
            ("Microsoft Project and EPM 2010",
             "Enterprise project portfolio management, master scheduling, resource allocation. Applied at "
             "Verssur Inc. for migration from Primavera to EPM across four continents."),
            ("Azure DevOps, Jira, and Confluence",
             "Agile project management, sprint planning, backlog management, CI/CD coordination for "
             "cloud-based ERP implementations at Nexus Innovation and ERA Consulting."),
        ]),
        ("Regulatory Compliance & Governance", [
            ("SAP GRC and NIST Cybersecurity Framework",
             "Governance, risk management, and compliance modules in SAP environments. Applied in contexts "
             "requiring SOX, FSMA, HIPAA, and cybersecurity compliance at PSP Investments."),
        ]),
    ]

    for cat_name, tools in categories:
        add_teal_sub_header(doc, cat_name)
        for tool_name, desc in tools:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.paragraph_format.space_after = Pt(6)
            p.paragraph_format.left_indent = Inches(0.2)
            add_run(p, f"{tool_name}: ", size=Pt(10), color=BLACK_RGB, bold=True)
            add_run(p, desc, size=Pt(10), color=BLACK_RGB)

    # Languages
    add_teal_sub_header(doc, "Languages")
    add_data_table(doc,
        ["Language", "Proficiency"],
        [["Portuguese", "Native"], ["English", "Fluent"], ["French", "Fluent"]],
        col_widths=[3000, 3000]
    )


def build_timeline(doc):
    add_navy_section_header(doc, "PROFESSIONAL CAREER TIMELINE")

    companies = [
        ("ERA Consulting Group Inc.", [(2023, 2026)]),
        ("Nexus Innovation", [(2022, 2023)]),
        ("Astek Canada (Sollio Agriculture)", [(2021, 2022)]),
        ("Cofomo (STM)", [(2021, 2021)]),
        ("Addmore Group (Resolute FP)", [(2017, 2018), (2019, 2021)]),
        ("PSP Investments", [(2018, 2019)]),
        ("CGI (SNC Valin)", [(2016, 2017)]),
        ("Verssur Inc.", [(2012, 2015)]),
        ("Allergan", [(2008, 2010)]),
    ]

    years = list(range(2008, 2027))
    n_cols = 1 + len(years)
    n_rows = 1 + len(companies)

    table = doc.add_table(rows=n_rows, cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    header_cells = table.rows[0].cells
    set_cell_shading(header_cells[0], NAVY)
    set_cell_margins(header_cells[0], 20, 20, 40, 40)
    p0 = header_cells[0].paragraphs[0]
    p0.alignment = WD_ALIGN_PARAGRAPH.LEFT
    add_run(p0, "Company", size=Pt(8), color=WHITE_RGB, bold=True)

    for j, year in enumerate(years):
        cell = header_cells[j + 1]
        set_cell_shading(cell, NAVY)
        set_cell_margins(cell, 20, 20, 10, 10)
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        add_run(p, f"'{year % 100:02d}", size=Pt(7), color=WHITE_RGB, bold=True)

    for i, (name, active_ranges) in enumerate(companies):
        row = table.rows[i + 1]
        bg = LIGHT_GRAY if i % 2 == 0 else WHITE

        name_cell = row.cells[0]
        set_cell_shading(name_cell, bg)
        set_cell_margins(name_cell, 15, 15, 40, 20)
        p = name_cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        add_run(p, name, size=Pt(7.5), color=BLACK_RGB)

        for j, year in enumerate(years):
            cell = row.cells[j + 1]
            active = any(start <= year <= end for start, end in active_ranges)
            set_cell_shading(cell, TEAL if active else bg)
            set_cell_margins(cell, 15, 15, 5, 5)
            cell.paragraphs[0].paragraph_format.space_before = Pt(0)
            cell.paragraphs[0].paragraph_format.space_after = Pt(0)

    add_paragraph_text(doc,
        "Total Working Days (without overlap): 5,100+ days  |  "
        "Career Span: May 2008 \u2013 Present (over 17 years)",
        size=Pt(9), color=DARK_GRAY_RGB, italic=True,
        alignment=WD_ALIGN_PARAGRAPH.CENTER, space_before=Pt(6)
    )


def _add_exp(doc, company, role, period, location, website, about, resps, impacts):
    add_company_box(doc, company, role, period, location, website, about)
    add_teal_sub_header(doc, "Key Responsibilities & Achievements")
    for r in resps:
        add_bullet(doc, r)
    add_teal_sub_header(doc, "Strategic Impacts & Results")
    for imp in impacts:
        add_bullet(doc, imp)
    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(2)
    spacer.paragraph_format.space_after = Pt(8)


def build_experience(doc):
    add_navy_section_header(doc, "PROFESSIONAL EXPERIENCE")

    _add_exp(doc,
        "ERA Consulting Group Inc.",
        "Project Coordinator (PCO) / ERP Project Manager",
        "August 2023 \u2013 Present",
        "4 Pl. du Commerce #310, Verdun, QC H3E 1J4, Canada",
        "https://www.groupeconseilera.com/en/",
        "ERA Consulting Group Inc. is a Canadian consulting firm of over 120 professionals specializing "
        "in ERP business solutions and e-commerce, with over 15 years in the market, recognized for "
        "expertise in Microsoft Dynamics 365 Business Central.",
        [
            "Manages all phases of ERP implementation projects from planning through execution and delivery, "
            "ensuring alignment between project objectives and client business needs across multiple concurrent engagements.",
            "Organizes and coordinates internal and external resources for ERP project execution, including "
            "cross-functional teams of developers, business analysts, and functional consultants.",
            "Led the end-to-end implementation of Microsoft Business Central 365 SaaS for Souris Mini, "
            "a Canadian retail company with multiple retail locations, achieving full go-live within planned timeline and budget.",
            "Developed and delivered structured ERP training programs for 50+ end users at Souris Mini, "
            "ensuring effective system adoption across finance, operations, and sales departments.",
            "Manages project budgets including resource allocation, cost tracking, and variance reporting, "
            "maintaining project financials within 10% of initial estimates.",
        ],
        [
            "Implemented Microsoft Business Central 365 SaaS at Souris Mini, enabling 10,000+ transactions "
            "per month through an integrated digital platform, replacing fragmented manual processes (Exhibit 2).",
            "Reduced Souris Mini\u2019s financial reporting cycle from 10 business days to 5 business days "
            "\u2014 a 50% improvement \u2014 through automated consolidation within Business Central (Exhibit 2).",
            "Trained 50+ end users across multiple departments at Souris Mini, achieving full system "
            "adoption as confirmed by Simon Letourneau, CFO of Souris Mini (Exhibit 2).",
            "Maintained a 95% client satisfaction rate across ERP implementation engagements.",
        ]
    )

    _add_exp(doc,
        "Nexus Innovation",
        "Agile Project Manager",
        "May 2022 \u2013 July 2023",
        "1751 Rue Richardson, Suite 4513, Montreal, QC H3K 1G6, Canada",
        "https://nexusinno.com/en/",
        "Nexus Innovation is a Montreal-based software development company specializing in cloud-based "
        "business solutions leveraging Microsoft technologies, particularly Microsoft Azure.",
        [
            "Coordinated internal resources and third-party vendors for multiple concurrent Microsoft "
            "Business Central implementation projects for small and medium enterprises.",
            "Defined, monitored, and delivered project scope, schedule, and budget aligned with client "
            "business objectives, applying Agile methodologies (Scrum and Kanban).",
            "Managed multiple ERP implementation projects simultaneously, ensuring quality, timeline, and budget.",
            "Directed implementation of project management tools, improving progress tracking by 40%.",
        ],
        [
            "Assisted over 10 SMEs in implementing Microsoft Business Central, resulting in an average "
            "25% increase in operational efficiency (Exhibit 29).",
            "Established a newly formed Business Central practice within Nexus Innovation, reducing "
            "project delivery timelines by 30%.",
            "Orchestrated cross-functional teams of up to 10 members, achieving milestones 15% ahead of schedule.",
            "Supervised project portfolio with combined budgets exceeding USD 5 million, maintaining "
            "a 95% project success rate.",
        ]
    )

    _add_exp(doc,
        "Astek Canada (Client: Sollio Agriculture)",
        "Project Management Consulting",
        "October 2021 \u2013 May 2022",
        "606 Rue Cathcart, Montreal, QC H3B 1K9, Canada",
        "https://astek.ca/",
        "Astek Canada is part of the Astek Group, operating in 22 countries with over 7,000 IT resources. "
        "Deni served Sollio Agriculture \u2014 a cooperative supporting farming families \u2014 through "
        "his consulting entity, 9364-3617 Quebec INC.",
        [
            "Ensured project costs were reported and monitored against budgets, with focus on ERP implementation.",
            "Facilitated Agile team events and managed risks associated with ERP implementation.",
            "Coordinated cross-functional teams in a FSMA-regulated environment.",
        ],
        [
            "Coordinated resource distribution across CAD 5 million budget.",
            "Implemented ERP solutions aligned with FSMA regulatory compliance, achieving zero findings "
            "in federal compliance audit.",
        ]
    )

    _add_exp(doc,
        "Cofomo (Client: STM)",
        "Senior IT Consultant / Project Control Officer",
        "April 2021 \u2013 October 2021",
        "1000 Rue De la Gaucheti\u00e8re O #1500, Montreal, QC H3B 4X5, Canada",
        "https://www.cofomo.com/",
        "Cofomo specializes in IT and business management solutions. Deni worked on a SAP implementation "
        "project at STM, a public enterprise serving Montreal\u2019s metropolitan population.",
        [
            "Administered project budget and cost tracking for SAP implementation (CAD 75 million total budget).",
            "Prepared, issued, and maintained the Master Time Schedule for the SAP program.",
            "Developed monthly and quarterly financial reports for the SAP implementation.",
        ],
        [
            "Contributed to financial governance of a CAD 75 million SAP implementation program (Exhibit 29).",
            "Refined resource planning, leading to more efficient team utilization.",
        ]
    )

    _add_exp(doc,
        "Addmore Group (Client: Resolute Forest Products)",
        "Project Management Consulting",
        "August 2017 \u2013 July 2018 and April 2019 \u2013 May 2021",
        "123 Sheppard Ave E, North York, ON M2N 3A5, Canada",
        "https://www.addmoregroup.com/",
        "Addmore Group, established in 1992, is specialized in SAP staffing solutions. Deni served "
        "Resolute Forest Products, a company specializing in market pulp, tissue, wood products, and paper, "
        "through his consulting entity, 9364-3617 Quebec INC.",
        [
            "Participated in resource planning and forecasting for SAP implementation across 30+ locations.",
            "Extracted and analyzed financial data from SAP systems for comprehensive reporting.",
            "Established KPIs to measure SAP implementation efficiency and success.",
            "Provided guidance and training on SAP project management best practices.",
        ],
        [
            "Played a fundamental role in a USD 75 million global SAP/ERP solution design and implementation "
            "across 30+ locations, benefiting 8,000+ end users (Exhibit 29).",
            "Automated financial consolidation using SAP BPC across 30+ locations and 5 currencies, reducing "
            "month-end closing from 15 days to 6 days \u2014 a 60% improvement \u2014 freeing approximately "
            "USD 1.2 million in annual operational costs (Exhibit 29).",
            "Supported SAP integration with USD 35 million budget, achieving 25% improvement in process efficiency.",
            "Established control structures resulting in 15% cost savings across the project lifecycle.",
        ]
    )

    _add_exp(doc,
        "PSP Investments",
        "Senior Analyst, IT Governance and Planning",
        "April 2018 \u2013 April 2019",
        "1250 Boul. Ren\u00e9-L\u00e9vesque O #900, Montreal, QC H3B 4W8, Canada",
        "https://www.investpsp.com/en/",
        "PSP Investments is one of Canada\u2019s largest pension fund managers. As of March 2023, PSP had "
        "net assets of CAD 243.7 billion and an annualized net return of 9.2% over 10 years.",
        [
            "Managed budgetary process and cost tracking for IT projects (USD 50 million total budget).",
            "Produced monthly governance reports reflecting key PMO OKRs.",
            "Identified financial and operational risks with effective mitigation strategies.",
        ],
        [
            "Supervised USD 50 million annual IT budget with optimal resource allocation (Exhibit 29).",
            "Implemented cost monitoring system reducing budget overrun incidents by 20%.",
            "Improved project portfolio performance by 18% through standardized practices.",
        ]
    )

    _add_exp(doc,
        "CGI (Client: SNC Valin / Atkins SNC)",
        "IT Management Consultant",
        "May 2016 \u2013 August 2017",
        "1350 Ren\u00e9-L\u00e9vesque Blvd W, Montreal, QC H3G 1T4, Canada",
        "https://www.cgi.com/canada/en-ca",
        "CGI is one of the world\u2019s largest IT and business consulting firms, with over 40 years of growth.",
        [
            "Managed budgetary and cost tracking for the project portfolio.",
            "Configured administrative management including treasury, accounting, and audit.",
            "Analyzed ROI and Value Added metrics to optimize financial efficiency.",
        ],
        [
            "Managed USD 10 million portfolio with 8,000 person-days, ensuring on-time delivery.",
            "Ensured adherence to PMO processes, achieving 80% compliance rate.",
        ]
    )

    _add_exp(doc,
        "Verssur Inc.",
        "Project Manager",
        "December 2012 \u2013 March 2015",
        "709 Rue St-Vallier E, Quebec, QC G1K 3P9, Canada",
        None,
        "Verssur Inc. was a technology consulting company providing IT consulting and project management "
        "services across multiple international markets on four continents.",
        [
            "Developed and controlled project plans for international clients across four continents.",
            "Supported migration from Primavera to Microsoft EPM 2010.",
            "Trained administrative resources in IT tools and systems.",
        ],
        [
            "Supported Verssur\u2019s expansion across four continents through effective project management.",
            "Managed complete project lifecycles: 15% under budget, 90% on-time delivery rate.",
            "Led 10 proposal processes, contributing to 30% increase in project approvals.",
            "Reduced project risks by 25% and maintained cost variance within 10%.",
        ]
    )

    _add_exp(doc,
        "Allergan",
        "Accounting Analyst (SAP Finance)",
        "May 2008 \u2013 May 2010",
        "Av. Eng. Luis Carlos Berrini, 105, S\u00e3o Paulo, SP, Brazil",
        None,
        "Allergan Produtos Farmac\u00eauticos Ltda is a subsidiary of Allergan, a global healthcare company "
        "specializing in pharmaceutical products for ophthalmological, neurological, and dermatological conditions.",
        [
            "Performed accounting and reconciliation using SAP, ensuring compliance with standards.",
            "Controlled inventory in transit and foreign exchange variations in a multinational context.",
            "Coordinated intercompany transactions ensuring proper accounting and reconciliation.",
        ],
        [
            "Improved in-transit inventory control, enhancing management\u2019s decision-making capacity.",
            "Developed detailed financial reports for corporate headquarters using SAP.",
            "Optimized fixed asset control, aligning resources with operational needs.",
        ]
    )


def build_contributions(doc):
    add_navy_section_header(doc, "TECHNICAL CONTRIBUTIONS & PROPRIETARY METHODOLOGY")

    add_teal_sub_header(doc, "DRM Success Framework \u2014 Proprietary Methodology")

    add_paragraph_text(doc,
        "Over the course of 15+ years of professional practice, Deni Ruben Moreira developed a "
        "structured, proprietary methodology for implementing integrated digital transformation "
        "solutions in small and medium enterprises. The DRM Success Framework is a five-phase approach:"
    )

    phases = [
        ("Phase 1: Operational Diagnostic (4\u20136 weeks)",
         "Assessment of digital maturity across five dimensions: technology governance, regulatory "
         "compliance, workforce capability, operational efficiency, and business agility. Identification "
         "of 3\u20135 high-impact areas for priority transformation."),
        ("Phase 2: Critical Process Mapping (6\u20138 weeks)",
         "Mapping of 100\u2013150 critical operational processes, classified by impact category. "
         "Identification of RPA automation candidates and regulatory compliance requirements."),
        ("Phase 3: Solution Design and Selection (4\u20136 weeks)",
         "Technical evaluation of platform alternatives (SAP Business One, Microsoft Business Central). "
         "Design of integrated technical architecture and prioritized implementation roadmap."),
        ("Phase 4: Phased Implementation (12\u201318 months)",
         "Implementation in 3\u20134 phases with quantifiable milestones. Continuous workforce training "
         "(4 structured modules). Organizational change management governance."),
        ("Phase 5: Post-Implementation Optimization (6\u201312 months)",
         "KPI monitoring, process adjustments based on real operational data, and preparation for "
         "subsequent improvement iterations."),
    ]
    for phase_name, desc in phases:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        p.paragraph_format.space_after = Pt(4)
        p.paragraph_format.left_indent = Inches(0.2)
        add_run(p, f"{phase_name}: ", size=Pt(10), color=NAVY_RGB, bold=True)
        add_run(p, desc, size=Pt(10), color=BLACK_RGB)

    add_paragraph_text(doc,
        "This methodology has been validated through the Souris Mini implementation (Exhibit 2) "
        "and documented in the peer-reviewed article \u201cDigital Transformation in U.S. SMEs: "
        "A Repeatable ERP Playbook Backed by a Real Case\u201d (Exhibit 12).",
        size=Pt(10), italic=True, color=DARK_GRAY_RGB
    )


def build_publications(doc):
    add_navy_section_header(doc, "PUBLICATIONS & PEER REVIEW ACTIVITY")

    add_paragraph_text(doc,
        "Deni Ruben Moreira has authored three peer-reviewed articles published in international "
        "journals, focused on ERP implementation strategies, digital transformation for SMEs, "
        "and AI-enhanced enterprise systems."
    )

    pubs = [
        {
            "title": "Critical Review of Strategies for Reducing ERP Failure in Small and Medium Enterprises",
            "journal": "ACADEMIA \u2014 A Multidisciplinary Journal",
            "vol": "Vol. 4, Issue 4, 2025",
            "doi": "10.63056/ACAD.004.04.1435",
            "impact": "Critical analysis of factors contributing to ERP implementation failure in SMEs, "
                      "synthesizing empirical evidence from multiple industry studies. Proposes a structured "
                      "mitigation framework based on 10+ ERP implementations. Contributes to understanding "
                      "of why SMEs face disproportionately higher ERP failure rates (Exhibit 11).",
            "exhibit": "Exhibit 11",
        },
        {
            "title": "Digital Transformation in U.S. SMEs: A Repeatable ERP Playbook Backed by a Real Case",
            "journal": "CMSRV \u2014 A Journal of Management Research",
            "vol": "Vol. 3, Issue 8, 2025",
            "doi": "10.5281/zenodo.18692716",
            "impact": "Presents a repeatable methodology for ERP implementation in U.S. SMEs, documenting "
                      "the DRM Success Framework and validating it through a detailed case study of a "
                      "successful Microsoft Business Central implementation. Demonstrates that a structured, "
                      "phased approach significantly reduces implementation risk (Exhibit 12).",
            "exhibit": "Exhibit 12",
        },
        {
            "title": "AI-Enhanced ERP Systems: Driving Digital Transformation in SMEs by Improving Efficiency",
            "journal": "Journal of Media Horizons (JMH)",
            "vol": "Vol. 6, Issue 7, 2025",
            "doi": "10.5281/zenodo.18138880",
            "impact": "Examines integration of AI capabilities within ERP systems as a driver of digital "
                      "transformation for SMEs. Analyzes predictive analytics, automated anomaly detection, "
                      "and intelligent process automation. Positions the author at the intersection of "
                      "ERP expertise and AI-driven innovation (Exhibit 13).",
            "exhibit": "Exhibit 13",
        },
    ]

    for pub in pubs:
        add_evidence_block(doc,
            [("Title", pub["title"]), ("Journal", pub["journal"]),
             ("Volume/Issue", pub["vol"]), ("DOI", pub["doi"]), ("Type", "Peer-reviewed article")],
            pub["impact"],
            f"[THUMBNAIL \u2014 {pub['exhibit']}]"
        )

    add_teal_sub_header(doc, "Peer Review Activity")
    add_paragraph_text(doc,
        "Invited peer reviewer for SAMRIDDHI \u2014 A Journal of Management & Research, completing "
        "two manuscript evaluations in December 2025 (Exhibits 14\u201317)."
    )

    for i, code in enumerate(["SAMR-061", "SAMR-062"]):
        add_evidence_block(doc,
            [("Journal", "SAMRIDDHI \u2014 A Journal of Management & Research"),
             ("Code", code), ("Date", "December 2025"), ("Type", "Invited peer reviewer")],
            f"Provided detailed technical review assessing methodology, findings, and practical "
            f"implications for SME digital transformation practitioners (Exhibits {14+i*2}\u2013{15+i*2}).",
            f"[THUMBNAIL \u2014 Exhibit {14+i*2}]"
        )


def build_academic(doc):
    add_navy_section_header(doc, "ACADEMIC BACKGROUND")

    degrees = [
        ("Business Analyst of Information Technology LCA.EM",
         "Montreal College of Information Technology", "January 9, 2020",
         "1255 Blvd Robert-Bourassa #200, Montreal, QC H3B 3B2, Canada",
         "Specialized program bridging business requirements with IT solutions. Combined with the BBA, "
         "evaluated by GEO Credential Services as equivalent to a Master of Science in Project "
         "Management in the United States (Exhibit 3).", "Exhibit 8"),
        ("Bachelor of Business Administration",
         "Universidade Anhembi Morumbi", "January 21, 2009",
         "R. Casa do Ator, 275 \u2014 Vila Ol\u00edmpia, S\u00e3o Paulo, SP, Brazil",
         "Four-year BBA program establishing foundation in business management, strategic planning, "
         "organizational leadership. Evaluated by WES (Exhibit 4) and GEO (Exhibit 3) for U.S. "
         "degree equivalency.", "Exhibit 9"),
        ("Postgraduate Program in Marketing and Sales Management",
         "Universidade Anhembi Morumbi", "June 30, 2007",
         "R. Casa do Ator, 275 \u2014 Vila Ol\u00edmpia, S\u00e3o Paulo, SP, Brazil",
         "Specialized postgraduate program in marketing and sales management, adding expertise "
         "in market analysis, strategic planning, and commercial strategy.", "Exhibit 10"),
    ]

    for title, inst, date, loc, impact, exhibit in degrees:
        add_evidence_block(doc,
            [("Program", title), ("Institution", inst),
             ("Graduation Date", date), ("Location", loc)],
            impact, f"[THUMBNAIL \u2014 {exhibit}]"
        )

    add_teal_sub_header(doc, "Credential Evaluation \u2014 U.S. Degree Equivalency")
    add_paragraph_text(doc,
        "The combined educational credentials \u2014 BBA from Universidade Anhembi Morumbi (2009) "
        "and Business Analyst of IT from Montreal College (2020) \u2014 were evaluated by GEO "
        "Credential Services as equivalent to a Master of Science in Project Management in the "
        "United States (Exhibit 3). Additional course-by-course evaluation by WES (Exhibit 4)."
    )


def build_licenses_and_courses(doc):
    add_navy_section_header(doc, "PROFESSIONAL LICENSES, CERTIFICATIONS & COURSES")

    certs = [
        ("Project Management Professional (PMP)", "Project Management Institute (PMI)",
         "#3770976", "February 2024", "Valid through February 2027",
         "Most recognized PM credential worldwide, held by 1.4M+ professionals. Requires 4,500+ hours "
         "of PM experience and passing a 180-question exam (Exhibit 24).", "Exhibit 24"),
        ("SAP Certified Application Associate \u2014 SAP S/4HANA for Management Accounting",
         "SAP SE", None, "June 13, 2021", "Active",
         "Validates proficiency in SAP S/4HANA Management Accounting: cost center accounting, "
         "internal orders, profitability analysis, product cost controlling (Exhibit 22).", "Exhibit 22"),
        ("PMI Disciplined Agile Scrum Master (DASM)", "Project Management Institute (PMI)",
         None, None, "Active",
         "Validates Agile and Scrum proficiency within the Disciplined Agile framework. Enables hybrid "
         "predictive/Agile approach for ERP implementations in SMEs (Exhibit 23).", "Exhibit 23"),
        ("Agile Project Management", "Udemy", None, "February 2026", None,
         "Covers Agile principles including Scrum/Waterfall hybrid methodologies, sprint planning, "
         "and iterative delivery (Exhibit 18).", "Exhibit 18"),
    ]

    for title, issuer, num, date, valid, impact, exhibit in certs:
        meta = [("Certification", title), ("Issuing Entity", issuer)]
        if num:
            meta.append(("Number", num))
        if date:
            meta.append(("Date", date))
        if valid:
            meta.append(("Status", valid))
        add_evidence_block(doc, meta, impact, f"[THUMBNAIL \u2014 {exhibit}]")


def build_affiliations(doc):
    add_navy_section_header(doc, "PROFESSIONAL AFFILIATIONS & ASSOCIATIONS")

    add_evidence_block(doc,
        [("Organization", "Institute of Electrical and Electronics Engineers (IEEE)"),
         ("Member Number", "101975995"),
         ("Grade", "Senior Member (elevated February 2026)"),
         ("Section", "Montreal Section"),
         ("Valid Through", "December 31, 2026")],
        "IEEE is the world\u2019s largest technical professional organization with 400,000+ members "
        "across 160 countries. Senior Member is the highest grade members can apply for, requiring "
        "10+ years of professional practice with 5+ years of significant performance. Only ~10% of "
        "IEEE members hold this grade (Exhibits 5\u20137).",
        "[THUMBNAIL \u2014 Exhibits 5\u20137]"
    )

    add_evidence_block(doc,
        [("Organization", "Project Management Institute (PMI)"),
         ("Member Number", "2741761"),
         ("Type", "Certified Member"),
         ("Chapter", "Montreal Chapter"),
         ("Period", "September 2022 \u2013 Present")],
        "PMI is the world\u2019s leading PM association with 700,000+ members. Deni holds both PMP "
        "and DASM credentials (Exhibits 24\u201325).",
        "[THUMBNAIL \u2014 Exhibits 24\u201325]"
    )


def build_proposed_endeavors(doc):
    add_navy_section_header(doc, "PROJETO EB-2 NIW \u2014 PROPOSED ENDEAVORS")

    add_paragraph_text(doc,
        "Deni Ruben Moreira has founded DRM Solutions LLC, registered in Dallas-Fort Worth, Texas, "
        "to pursue integrated digital transformation consulting for American small and medium enterprises. "
        "The proposed endeavor addresses a documented structural gap in the U.S. market: only 38% of SMEs "
        "with 20\u2013100 employees have implemented integrated ERP systems (Department of Commerce, 2023), "
        "creating both operational inefficiencies and regulatory compliance risks in critical sectors. "
        "The endeavor is structured around three strategic pillars, each aligned with federal legislative "
        "priorities and supported by verifiable market data."
    )

    # Pillar A
    add_teal_sub_header(doc, "Pillar A: National Digital Resilience Platform for SMEs")
    add_paragraph_text(doc,
        "Design and implementation of integrated digital transformation solutions (ERP + BI + process "
        "automation + regulatory compliance) for American SMEs in critical sectors. Target: deploy in "
        "12 rural counties in Texas within the first three years, addressing the documented digital "
        "maturity gap affecting 62% of American SMEs that have not implemented integrated ERP systems. "
        "Expected impact: contribute to reducing an estimated USD 1.8 billion per year in operational "
        "inefficiencies affecting underserved SMEs."
    )
    for b in [
        "Market size: The ERP software market for SMEs in the United States is projected to reach "
        "USD 50.7 billion by 2030, growing at a CAGR of 10.7% (Source: Grand View Research, 2024).",
        "BLS Occupational Code: 15-1299.09 (Information Technology Project Managers) \u2014 projected "
        "16% growth 2024\u20132034, significantly faster than average (Bureau of Labor Statistics).",
        "Federal alignment: CHIPS and Science Act (Section 225 \u2014 MEP), Infrastructure Investment "
        "and Jobs Act (Section 60102 \u2014 Digital Equity), Small Business Act (Section 7(a) \u2014 SCORE).",
        "Target sectors: Food & Agriculture (FSMA compliance), Healthcare (HIPAA), Financial Services "
        "(GLBA/SOX), Manufacturing & Distribution.",
    ]:
        add_bullet(doc, b)

    # Pillar B
    add_teal_sub_header(doc, "Pillar B: National Technical Training Program for Digital Workforce")
    add_paragraph_text(doc,
        "Design and delivery of structured corporate training programs (four modules: ERP fundamentals, "
        "business intelligence, regulatory compliance, and organizational change management) to build "
        "technical capacity within American SME workforces. Target: train 3,000 professionals over five "
        "years, contributing to reducing the documented shortage of approximately 83,000 ERP specialists "
        "in the United States (Bureau of Labor Statistics)."
    )
    for b in [
        "Market size: U.S. corporate training market valued at USD 101.8 billion (2024), with "
        "technology training as fastest-growing segment at 12.3% CAGR (Source: Training Industry Report).",
        "BLS Code: 13-1151 (Training and Development Specialists) \u2014 6% growth 2024\u20132034.",
        "Federal alignment: Workforce Innovation and Opportunity Act (WIOA) \u2014 Section 3 & 134. "
        "DOL invested USD 3.2 billion in WIOA training programs in 2024.",
    ]:
        add_bullet(doc, b)

    # Pillar C
    add_teal_sub_header(doc, "Pillar C: Strategic Consulting and AI-Powered Proprietary Tool")
    add_paragraph_text(doc,
        "Development of a digital maturity scorecard and AI-powered diagnostic tool that enables SMEs "
        "to assess technological readiness and receive structured recommendations for digital "
        "transformation. This tool operationalizes the DRM Success Framework Phase 1 in a scalable format."
    )
    for b in [
        "Market size: Global AI in ERP market projected to reach USD 8.2 billion by 2028, growing "
        "at 23.4% CAGR (Source: MarketsandMarkets, 2024).",
        "BLS Code: 15-2051 (Data Scientists) \u2014 36% growth 2024\u20132034.",
        "Federal alignment: Executive Order 14110 (AI), NIST AI Risk Management Framework, CISA Act.",
    ]:
        add_bullet(doc, b)

    # Comparative table
    add_teal_sub_header(doc, "Comparative Analysis of Proposed Endeavors")
    add_data_table(doc,
        ["Dimension", "Pillar A: Digital Resilience", "Pillar B: Training", "Pillar C: AI Diagnostic"],
        [
            ["Target Market", "SMEs (20\u2013500 employees)", "SME workforces", "SMEs all sizes"],
            ["BLS Code", "15-1299.09", "13-1151", "15-2051"],
            ["Growth Rate", "16% (2024\u20132034)", "6% (2024\u20132034)", "36% (2024\u20132034)"],
            ["Federal Policy", "CHIPS Act, Digital Equity", "WIOA", "EO 14110, NIST AI"],
            ["Year 1 Revenue", "USD 475K", "USD 90K", "R&D Phase"],
            ["5-Year Target", "50+ implementations", "3,000 professionals", "SaaS platform"],
            ["Primary Sector", "Food, Healthcare, Finance", "Cross-sector", "Cross-sector"],
        ],
        col_widths=[2200, 2700, 2700, 2700]
    )

    # Connection
    add_teal_sub_header(doc, "Connection to Professional Experience")
    add_paragraph_text(doc,
        "Every element of the proposed endeavor draws directly from Deni Ruben Moreira\u2019s documented "
        "professional trajectory: 15+ years of ERP implementation experience across SAP and Microsoft "
        "Business Central, demonstrated success with SME digital transformation (10+ implementations at "
        "Nexus Innovation, Souris Mini case at ERA Consulting), regulatory compliance across four sectors "
        "(pharmaceutical, agricultural, financial, public transportation), and a published academic record "
        "documenting the methodology and its validation. The proposed endeavor aligns with the CHIPS and "
        "Science Act, WIOA, Infrastructure Investment and Jobs Act, Small Business Act, and NIST "
        "Cybersecurity Framework \u2014 all identifying digital transformation of American SMEs as a "
        "national priority."
    )


def build_recommendation_letters(doc):
    add_navy_section_header(doc, "RECOMMENDATION LETTERS & EXPERT OPINIONS")
    add_data_table(doc,
        ["#", "Author", "Title / Organization", "Exhibit"],
        [
            ["1", "Florian Schmitt, CISSP", "IT & Cybersecurity Director, ERA Consulting (Jan 2026)", "Exhibit 19"],
            ["2", "Urbano Cerqueira Matos Jr", "Technical Endorsement \u2014 DRM Success Framework", "Exhibit 20"],
            ["3", "Lori Kilgour", "Professional reference", "Annex"],
            ["4", "Hugues Tremblay", "Resolute / IBM (professional reference)", "Annex"],
            ["5", "C\u00e9line Le Bon", "BRP / SNC-Lavalin (professional reference)", "Annex"],
            ["6", "Francisco D. Edgar", "CEO, Verssur Inc.", "Exhibit 20"],
            ["7", "Dr. Tamjid Al Rahat", "Expert Opinion Letter (AWS)", "EOL"],
            ["8", "Dr. Nihad Bassis", "Expert Opinion Letter", "EOL"],
        ],
        col_widths=[600, 2800, 4200, 1500]
    )


def build_exhibit_index(doc):
    add_navy_section_header(doc, "EXHIBIT INDEX")
    exhibits = [
        ("Exhibit 1", "This R\u00e9sum\u00e9"),
        ("Exhibit 2", "Reference Letter \u2014 Simon Letourneau, CFO, Souris Mini (Jan 2026)"),
        ("Exhibit 3", "Credential Evaluation \u2014 GEO Credential Services"),
        ("Exhibit 4", "Course-by-Course Evaluation \u2014 World Education Services (WES)"),
        ("Exhibit 5", "IEEE Senior Membership Certificate (February 2026)"),
        ("Exhibit 6", "IEEE Senior Membership Card"),
        ("Exhibit 7", "IEEE Senior Membership \u2014 Congratulations Email"),
        ("Exhibit 8", "Business Analyst of IT Diploma \u2014 Montreal College (2020)"),
        ("Exhibit 9", "BBA Diploma \u2014 Universidade Anhembi Morumbi (2009)"),
        ("Exhibit 10", "Marketing and Sales Certificate \u2014 Anhembi Morumbi (2007)"),
        ("Exhibit 11", "Publication \u2014 ACADEMIA Journal (2025)"),
        ("Exhibit 12", "Publication \u2014 CMSR Journal (2025)"),
        ("Exhibit 13", "Publication \u2014 JMH (2025)"),
        ("Exhibit 14", "Peer Review Invitation \u2014 SAMRIDDHI (SAMR-061)"),
        ("Exhibit 15", "Peer Review Certificate \u2014 SAMRIDDHI (SAMR-061)"),
        ("Exhibit 16", "Peer Review Invitation \u2014 SAMRIDDHI (SAMR-062)"),
        ("Exhibit 17", "Peer Review Certificate \u2014 SAMRIDDHI (SAMR-062)"),
        ("Exhibit 18", "Agile Project Management \u2014 Udemy (February 2026)"),
        ("Exhibit 19", "Reference Letter \u2014 Florian Schmitt, ERA Consulting (Jan 2026)"),
        ("Exhibit 20", "Reference Letter \u2014 Francisco D. Edgar, Verssur Inc."),
        ("Exhibit 21", "HR Attestation \u2014 ERA Consulting Group (Oct 2025)"),
        ("Exhibit 22", "SAP S/4HANA Certification (June 2021)"),
        ("Exhibit 23", "DASM Certificate \u2014 PMI"),
        ("Exhibit 24", "PMP Certification \u2014 PMI (#3770976)"),
        ("Exhibit 25", "PMI Membership Certificate and Card"),
        ("Exhibit 26", "High School Transcript"),
        ("Exhibit 27", "Transcript \u2014 Montreal College"),
        ("Exhibit 28", "Transcript \u2014 Universidade Anhembi Morumbi"),
        ("Exhibit 29", "HR Letters / Employment Attestations \u2014 9 companies"),
        ("Exhibit 30", "DRM Solutions LLC \u2014 Certificate of Filing (TX)"),
    ]
    add_data_table(doc,
        ["Exhibit", "Description"],
        [[ex, desc] for ex, desc in exhibits],
        col_widths=[1800, 8400]
    )


# =============================================================================
# MAIN BUILD
# =============================================================================

def build_resume():
    print("=" * 70)
    print("R\u00c9SUM\u00c9 EB-2 NIW \u2014 DENI RUBEN MOREIRA")
    print("V4 DNA Visual System \u2014 100% Garamond + Navy/Teal")
    print("=" * 70)

    print("\n[1/12] Setting up document...")
    doc = setup_document()

    print("[2/12] Building Summary...")
    build_summary(doc)

    print("[3/12] Building Tools & Software...")
    build_tools(doc)

    print("[4/12] Building Professional Timeline...")
    build_timeline(doc)

    print("[5/12] Building Professional Experience...")
    build_experience(doc)

    print("[6/12] Building Technical Contributions...")
    build_contributions(doc)

    print("[7/12] Building Publications & Peer Review...")
    build_publications(doc)

    print("[8/12] Building Academic Background...")
    build_academic(doc)

    print("[9/12] Building Licenses & Courses...")
    build_licenses_and_courses(doc)

    print("[10/12] Building Professional Affiliations...")
    build_affiliations(doc)

    print("[11/12] Building Proposed Endeavors...")
    build_proposed_endeavors(doc)

    print("[12/12] Building Recommendation Letters & Exhibit Index...")
    build_recommendation_letters(doc)
    build_exhibit_index(doc)

    # Closing
    add_paragraph_text(doc,
        "This r\u00e9sum\u00e9 was prepared in support of the I-140 Petition for EB-2 National Interest "
        "Waiver classification filed on behalf of Deni Ruben Moreira. All facts, dates, figures, and "
        "claims presented herein are supported by documentary evidence referenced as Exhibits.",
        size=Pt(9), color=MED_GRAY_RGB, italic=True,
        alignment=WD_ALIGN_PARAGRAPH.CENTER, space_before=Pt(20)
    )

    # Save
    timestamp = datetime.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    filename = f"RESUME_EB2NIW_DENI_RUBEN_MOREIRA_{timestamp}.docx"
    output_path = os.path.join(RESUME_FOLDER, filename)
    output_path_main = os.path.join(DENI_FOLDER, filename)

    os.makedirs(RESUME_FOLDER, exist_ok=True)
    doc.save(output_path)
    doc.save(output_path_main)

    print(f"\n{'=' * 70}")
    print(f"SAVED: {output_path}")
    print(f"SAVED: {output_path_main}")
    print(f"{'=' * 70}")

    return output_path_main


if __name__ == "__main__":
    output = build_resume()
    print(f"\nDone. Output: {output}")
