#!/usr/bin/env python3
"""
RESUME EB-1A Generator — Guilherme Caldeira De Lello
SOC: 11-9041.00 Architectural and Engineering Managers
Generated by Petition Engine
"""

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml
import os

# ─── CONFIG ────────────────────────────────────────────────────
OUTPUT_DIR = "/Users/paulo1844/Documents/_PROEX (A COMPLEMENTAR)/_2. MEUS CASOS/2026/Guilherme Caldeira De Lello OS5195 15DEZ25 Kayenne AJUSTE/_Forjado por Petition Engine"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "resume_eb1a_Guilherme_Caldeira_De_Lello.docx")

# Colors
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
MED_GRAY = RGBColor(0x66, 0x66, 0x66)
LIGHT_GRAY = RGBColor(0x99, 0x99, 0x99)
HEADER_BG = "D5E8F0"
BOX_BG = "F5F5F5"
BORDER_COLOR = "CCCCCC"

doc = Document()

# ─── PAGE SETUP ────────────────────────────────────────────────
for section in doc.sections:
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

# ─── STYLES ────────────────────────────────────────────────────
style = doc.styles['Normal']
font = style.font
font.name = 'Arial'
font.size = Pt(10.5)
font.color.rgb = BLACK
pf = style.paragraph_format
pf.line_spacing = 1.15
pf.space_after = Pt(6)


def set_font(run, size=10.5, bold=False, italic=False, color=BLACK, name='Arial'):
    run.font.name = name
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color


def add_section_title(text):
    """Add criterion section title — ALL CAPS, 14pt Bold, with page break before."""
    p = doc.add_paragraph()
    p.paragraph_format.page_break_before = True
    p.paragraph_format.space_before = Pt(24)
    p.paragraph_format.space_after = Pt(12)
    run = p.add_run(text.upper())
    set_font(run, size=14, bold=True)
    # Add thin separator line
    add_separator()
    return p


def add_subtitle(text):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(6)
    run = p.add_run(text)
    set_font(run, size=12, bold=True)
    return p


def add_body(text, space_after=6):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.line_spacing = 1.15
    run = p.add_run(text)
    set_font(run, size=10.5)
    return p


def add_separator():
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(6)
    # Thin line via border
    pPr = p._p.get_or_add_pPr()
    pBdr = parse_xml(
        f'<w:pBdr {nsdecls("w")}>'
        f'<w:bottom w:val="single" w:sz="4" w:space="1" w:color="{BORDER_COLOR}"/>'
        f'</w:pBdr>'
    )
    pPr.append(pBdr)


def add_evidence_block(title, fields, description, institutional_box=None):
    """
    Add a complete evidence block with [THUMBNAIL] placeholder and metadata.
    fields: list of (label, value) tuples
    description: string or list of strings (paragraphs)
    institutional_box: optional string for institutional context
    """
    # Table: 2 columns (thumbnail | metadata)
    table = doc.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False

    # Set column widths
    for cell in table.columns[0].cells:
        cell.width = Inches(1.1)
    for cell in table.columns[1].cells:
        cell.width = Inches(5.4)

    # Remove table borders
    tbl = table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else parse_xml(f'<w:tblPr {nsdecls("w")}/>')
    borders = parse_xml(
        f'<w:tblBorders {nsdecls("w")}>'
        '<w:top w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '<w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '<w:bottom w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '<w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '<w:insideH w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '<w:insideV w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
        '</w:tblBorders>'
    )
    existing_borders = tblPr.find(qn('w:tblBorders'))
    if existing_borders is not None:
        tblPr.remove(existing_borders)
    tblPr.append(borders)

    # Left cell: THUMBNAIL placeholder
    left_cell = table.cell(0, 0)
    left_cell.vertical_alignment = 1  # CENTER
    lp = left_cell.paragraphs[0]
    lp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = lp.add_run("[THUMBNAIL]")
    set_font(run, size=8, color=LIGHT_GRAY)

    # Add border to thumbnail cell
    tc = left_cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = parse_xml(
        f'<w:tcBorders {nsdecls("w")}>'
        f'<w:top w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
        f'<w:left w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
        f'<w:bottom w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
        f'<w:right w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
        f'</w:tcBorders>'
    )
    tcPr.append(tcBorders)
    # Set shading for placeholder
    shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{BOX_BG}" w:val="clear"/>')
    tcPr.append(shading)

    # Right cell: Metadata
    right_cell = table.cell(0, 1)
    # Clear default paragraph
    right_cell.paragraphs[0].clear()

    # Title
    tp = right_cell.paragraphs[0]
    run = tp.add_run(title)
    set_font(run, size=11, bold=True)
    tp.paragraph_format.space_after = Pt(4)

    # Fields
    for label, value in fields:
        fp = right_cell.add_paragraph()
        fp.paragraph_format.space_after = Pt(2)
        fp.paragraph_format.space_before = Pt(0)
        lrun = fp.add_run(f"{label}: ")
        set_font(lrun, size=10, bold=True)
        vrun = fp.add_run(value)
        set_font(vrun, size=10)

    # Description & Impact below the table
    if isinstance(description, str):
        description = [description]

    dp = doc.add_paragraph()
    dp.paragraph_format.space_before = Pt(8)
    dp.paragraph_format.space_after = Pt(4)
    drun = dp.add_run("Description & Impact/Relevance:")
    set_font(drun, size=10.5, bold=True)

    for para_text in description:
        bp = doc.add_paragraph()
        bp.paragraph_format.space_after = Pt(4)
        bp.paragraph_format.line_spacing = 1.15
        brun = bp.add_run(para_text)
        set_font(brun, size=10.5)

    # Institutional box
    if institutional_box:
        box_table = doc.add_table(rows=1, cols=1)
        box_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        box_cell = box_table.cell(0, 0)

        # Set background
        tc2 = box_cell._tc
        tcPr2 = tc2.get_or_add_tcPr()
        shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{BOX_BG}" w:val="clear"/>')
        tcPr2.append(shd)
        # Set border
        tcBdr = parse_xml(
            f'<w:tcBorders {nsdecls("w")}>'
            f'<w:top w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
            f'<w:left w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
            f'<w:bottom w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
            f'<w:right w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
            f'</w:tcBorders>'
        )
        tcPr2.append(tcBdr)

        bp2 = box_cell.paragraphs[0]
        bp2.paragraph_format.space_after = Pt(4)
        brun2 = bp2.add_run(institutional_box)
        set_font(brun2, size=9.5, italic=True, color=DARK_GRAY)

    # Spacing after block
    sp = doc.add_paragraph()
    sp.paragraph_format.space_after = Pt(12)


# ═══════════════════════════════════════════════════════════════
# BLOCO 1 — HEADER
# ═══════════════════════════════════════════════════════════════

# Title: RESUME
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
p.paragraph_format.space_after = Pt(6)
run = p.add_run("RESUME")
set_font(run, size=18, bold=True)

# Name
p2 = doc.add_paragraph()
p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
p2.paragraph_format.space_after = Pt(18)
run2 = p2.add_run("GUILHERME CALDEIRA DE LELLO")
set_font(run2, size=18, bold=True)

# Contact block
p3 = doc.add_paragraph()
p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
p3.paragraph_format.space_after = Pt(2)
run3 = p3.add_run("Contact")
set_font(run3, size=12, bold=True)

contact_lines = [
    "Phone: [VERIFICAR]",
    "E-mail: [VERIFICAR]",
    "Architectural and Engineering Manager | SOC/O*Net: 11-9041.00",
    "Address: [VERIFICAR]",
]
for line in contact_lines:
    cp = doc.add_paragraph()
    cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cp.paragraph_format.space_after = Pt(2)
    crun = cp.add_run(line)
    set_font(crun, size=10)

# ═══════════════════════════════════════════════════════════════
# BLOCO 2 — SUMMARY OF PROFESSIONAL QUALIFICATIONS
# ═══════════════════════════════════════════════════════════════

add_section_title("SUMMARY OF PROFESSIONAL QUALIFICATIONS")

add_body(
    "Guilherme Caldeira De Lello is a distinguished Architectural and Engineering Manager "
    "holding a Master of Science degree in Electrical Engineering from the Programa de "
    "Engenharia Eletrica (PEE/COPPE) at Universidade Federal do Rio de Janeiro (UFRJ) "
    "and a Bachelor of Engineering degree in Electronic and Computing Engineering from "
    "the same institution. With over sixteen years of sustained professional practice "
    "spanning advanced engineering management, large-scale educational technology "
    "infrastructure, and applied artificial intelligence research, Mr. De Lello has "
    "established himself as a preeminent figure at the intersection of engineering "
    "leadership and technological innovation in Brazil."
)

add_body(
    "As founder and principal engineering strategist of IP.TV LTDA and IP.TV LAB "
    "EDUCATION LTDA, Mr. De Lello has directed the conception, development, and "
    "deployment of mission-critical technology platforms serving government and "
    "institutional clients at extraordinary scale. His flagship initiative, the "
    "Centro de Midias SP (CMSP) platform, delivered to the Secretariat of Education "
    "of the State of Sao Paulo, enabled simultaneous access for over one million "
    "students and educators during the COVID-19 pandemic, representing one of the "
    "largest emergency educational technology deployments in Latin American history. "
    "This achievement was recognized by the Inter-American Development Bank (IDB) with "
    "the prestigious Gobernarte 2020 Award for Innovation in Citizen Management Services."
)

add_body(
    "Mr. De Lello's technical contributions extend to the frontier of applied machine "
    "learning and signal processing research. His peer-reviewed publications in IEEE "
    "proceedings and the Brazilian Society on Computational Intelligence (SBIC) journal "
    "have advanced the field of surface electromyography (sEMG)-based hand gesture "
    "recognition systems for prosthetic devices and assistive technologies, as well as "
    "weightless neural network architectures for nonintrusive load monitoring (NILM) in "
    "energy efficiency applications. His research, conducted at COPPE/UFRJ under the "
    "supervision of Prof. Markus Vinicius Santos Lima, achieved classification accuracy "
    "rates of 95.2% in six-gesture recognition systems, contributing directly to "
    "advancements in upper-limb rehabilitation technologies."
)

add_body(
    "His portfolio of original contributions includes four software programs registered "
    "with the Brazilian National Institute of Industrial Property (INPI), encompassing "
    "educational platforms, mobile assistive technology applications, and enterprise "
    "broadcast synchronization systems. The REALMS platform (INPI BR512023001278-5) and "
    "the Mano gesture-recognition application (INPI BR512018051989-0) represent "
    "proprietary innovations deployed across educational institutions and assistive "
    "technology contexts in Brazil and internationally."
)

add_body(
    "Mr. De Lello's career trajectory reflects a rare convergence of deep technical "
    "expertise in electronics engineering, neural network architectures, and signal "
    "processing with demonstrated executive-level capacity for managing complex, "
    "high-stakes technology projects at scale. His proposed endeavor in the United States "
    "centers on strategic engineering management and technology direction in "
    "infrastructure-critical sectors, including advanced automation, renewable energy "
    "systems, and AI-powered educational technology, areas identified as national "
    "priorities under Executive Order 14277 (Advancing Artificial Intelligence Education "
    "for American Youth, April 2025) and Executive Order 14278 (Preparing Americans for "
    "High-Paying Skilled Trade Jobs of the Future, April 2025). According to the U.S. "
    "Bureau of Labor Statistics (BLS, May 2024), Architectural and Engineering Managers "
    "(SOC 11-9041) command a national annual median wage of $165,370 and a mean wage of "
    "$172,290, reflecting the critical demand for professionals of Mr. De Lello's caliber "
    "in the American economy."
)

add_body(
    "His international recognition through four independent awards from distinguished "
    "institutions spanning three continents, his authorship of peer-reviewed scholarly "
    "articles published in indexed international venues, his demonstrable leadership of "
    "technology organizations delivering infrastructure at national scale, and his "
    "portfolio of registered intellectual property collectively establish a sustained "
    "record of extraordinary ability in the field of Architectural and Engineering "
    "Management."
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 3 — C1: RECEIPT OF AWARDS OR DISTINCTIONS
# ═══════════════════════════════════════════════════════════════

add_section_title("RECEIPT OF AWARDS OR DISTINCTIONS OF EXCELLENCE RECOGNIZED IN THE FIELD OF ACTIVITY")

add_body(
    "Mr. De Lello has been the recipient of multiple internationally recognized awards "
    "and distinctions conferred by independent organizations across three continents, "
    "each validating distinct dimensions of his professional excellence in engineering "
    "management and technology innovation. The following evidence blocks document four "
    "awards spanning a fifteen-year period (2009-2024), collectively demonstrating "
    "sustained recognition at the highest levels of the field."
)

# Award 1: Tech & Learning 2024
add_evidence_block(
    title="Tech & Learning Awards of Excellence — Best of 2024 (EduxGen.AI)",
    fields=[
        ("Related Criterion(s)", "Criterion 1 — Awards or Prizes"),
        ("Institution/Entity", "Tech & Learning Magazine"),
        ("Type of Evidence", "Award Certificate / Editorial Feature"),
        ("Date Issued", "31 January 2025"),
        ("Location", "United States (National Publication)"),
        ("Website/URL", "https://www.techlearning.com"),
    ],
    description=[
        "Mr. De Lello's EduxGen.AI platform was selected as a recipient of the Tech & Learning "
        "Awards of Excellence for Best of 2024, a distinction conferred annually by Tech & Learning "
        "Magazine, one of the most authoritative publications in the global educational technology "
        "sector. The award recognizes products and solutions that demonstrate exceptional innovation, "
        "pedagogical impact, and measurable value to educational institutions.",

        "EduxGen.AI represents a proprietary AI-powered educational platform developed under "
        "Mr. De Lello's engineering leadership at IP.TV LAB EDUCATION LTDA. The platform integrates "
        "advanced artificial intelligence capabilities with interactive learning methodologies, "
        "serving educational institutions and corporate training environments at scale. The "
        "selection process involved evaluation by the magazine's editorial board, comprising "
        "experienced educators, technology analysts, and industry specialists with expertise in "
        "assessing educational technology solutions.",
    ],
    institutional_box=(
        "Tech & Learning Magazine is a premier publication in the educational technology sector, "
        "serving educators, administrators, and technology professionals across the United States "
        "and internationally. Founded in 1980, the publication provides authoritative reviews, "
        "analysis, and recognition of innovations in K-12 and higher education technology. The "
        "annual Awards of Excellence program is widely regarded as one of the most prestigious "
        "distinction mechanisms in the EdTech industry."
    )
)

# Award 2: BID Gobernarte 2020
add_evidence_block(
    title="Inter-American Development Bank (IDB) Gobernarte Award 2020 — Innovation Category",
    fields=[
        ("Related Criterion(s)", "Criterion 1 — Awards or Prizes"),
        ("Institution/Entity", "Inter-American Development Bank (IDB / Banco Interamericano de Desenvolvimento)"),
        ("Type of Evidence", "International Award / Official IDB Press Release"),
        ("Date Issued", "07 December 2020"),
        ("Location", "Washington, D.C., United States (International Organization)"),
        ("Website/URL", "https://www.iadb.org"),
    ],
    description=[
        "The Centro de Midias SP (CMSP) platform, developed and deployed under Mr. De Lello's "
        "engineering leadership at IP.TV LTDA, was awarded the prestigious Gobernarte 2020 Prize "
        "in the Innovation Category by the Inter-American Development Bank (IDB). The seventh "
        "edition of the Gobernarte Prize evaluated 127 initiatives submitted by public "
        "institutions across 12 Latin American nations, with winners selected from five countries "
        "by a panel of five internationally recognized experts in public administration and "
        "technology innovation.",

        "The CMSP platform enabled the State of Sao Paulo to provide continuous educational "
        "access to over one million simultaneous users (students and educators) during the "
        "COVID-19 pandemic. Mr. De Lello's engineering team designed, built, and deployed the "
        "platform under emergency conditions, delivering a fully operational streaming and "
        "videoconferencing infrastructure within weeks. The IDB recognized this achievement as a "
        "paradigm of innovation in citizen management services, noting its exceptional scale, "
        "rapid deployment, and measurable impact on educational continuity.",
    ],
    institutional_box=(
        "The Inter-American Development Bank (IDB), headquartered in Washington, D.C., is the "
        "leading source of development financing for Latin America and the Caribbean. Established "
        "in 1959 with 48 member countries, the IDB provides loans, grants, and technical "
        "assistance to support economic and social development. The Gobernarte Prize, established "
        "in 2013, recognizes excellence and innovation in public administration across the region, "
        "with selection conducted by independent panels of international experts."
    )
)

# Award 3: WISE 2009
add_evidence_block(
    title="WISE Award 2009 — World Innovation Summit for Education (Qatar Foundation)",
    fields=[
        ("Related Criterion(s)", "Criterion 1 — Awards or Prizes"),
        ("Institution/Entity", "Qatar Foundation / WISE (World Innovation Summit for Education)"),
        ("Type of Evidence", "International Award / Conference Program Documentation"),
        ("Date Issued", "16-18 November 2009"),
        ("Location", "Doha, Qatar"),
        ("Website/URL", "https://www.wise-qatar.org"),
    ],
    description=[
        "Mr. De Lello's project on Distance Learning in the Amazon Forest was recognized at the "
        "inaugural World Innovation Summit for Education (WISE 2009), convened by the Qatar "
        "Foundation in Doha. WISE is a global initiative that brings together practitioners, "
        "policymakers, entrepreneurs, and thought leaders from over 100 countries to identify "
        "and disseminate innovative educational solutions addressing critical challenges.",

        "The Distance Learning in the Amazon Forest project demonstrated Mr. De Lello's early "
        "commitment to leveraging technology infrastructure for educational access in underserved "
        "regions. The project addressed the challenge of delivering quality education to remote "
        "communities in the Brazilian Amazon, where geographic isolation and infrastructure "
        "limitations create severe barriers to educational attainment. The WISE recognition "
        "validated the project's innovative approach to bridging these gaps through technology-"
        "mediated learning environments.",
    ],
    institutional_box=(
        "The Qatar Foundation for Education, Science and Community Development is a private, "
        "non-profit organization founded in 1995 by the Emir of Qatar. WISE (World Innovation "
        "Summit for Education) was established in 2009 as a global reference platform for new "
        "approaches in education through innovation. The summit convenes participants from over "
        "100 countries and its recognition programs are among the most selective in the global "
        "education sector."
    )
)

# Award 4: Assespro-RJ 2013
add_evidence_block(
    title="Assespro-RJ Best Companies Award 2013 — Best Telecommunications Solution & Best IT Infrastructure Solution",
    fields=[
        ("Related Criterion(s)", "Criterion 1 — Awards or Prizes"),
        ("Institution/Entity", "Associacao das Empresas Brasileiras de Tecnologia da Informacao (Assespro-RJ)"),
        ("Type of Evidence", "Industry Award / Official Correspondence with Award Seals"),
        ("Date Issued", "26 November 2013"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.assespro-rj.org.br"),
    ],
    description=[
        "VAT Tecnologia (subsequently known as Logica Tecnologia), under Mr. De Lello's technical "
        "leadership, received dual recognition at the 2013 Assespro-RJ Best Companies Award "
        "ceremony, winning both the Best Telecommunications Solution and Best IT Infrastructure "
        "Solution categories. The awarded product, SynCast IP.TV Sync, is an enterprise broadcast "
        "and streaming synchronization platform designed for large-scale corporate and institutional "
        "deployments.",

        "The Assespro-RJ awards are conferred through an independent evaluation process conducted "
        "by the technology industry association representing the leading information technology "
        "companies in the State of Rio de Janeiro. The dual-category recognition reflects the "
        "platform's exceptional performance across both telecommunications infrastructure and IT "
        "systems integration, affirming Mr. De Lello's capacity to deliver solutions that operate "
        "at the convergence of these domains.",
    ],
    institutional_box=(
        "Assespro-RJ (Associacao das Empresas Brasileiras de Tecnologia da Informacao, Regional "
        "Rio de Janeiro) is one of the oldest and most influential technology industry associations "
        "in Brazil, representing hundreds of IT companies in the State of Rio de Janeiro. Founded "
        "in 1976, its annual Best Companies Award program recognizes excellence across multiple "
        "technology categories, with evaluation conducted by panels of industry professionals and "
        "sector specialists."
    )
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 4 — C5: ORIGINAL CONTRIBUTIONS
# ═══════════════════════════════════════════════════════════════

add_section_title("ORIGINAL CONTRIBUTIONS OF MAJOR SIGNIFICANCE TO THE FIELD")

add_body(
    "Mr. De Lello's original contributions span two interconnected domains: (1) proprietary "
    "software platforms registered with the Brazilian National Institute of Industrial Property "
    "(INPI) that have been commercially deployed at national and international scale, and "
    "(2) peer-reviewed research innovations in machine learning, signal processing, and neural "
    "network architectures with direct applications in assistive technologies and energy "
    "efficiency. Each contribution documented below has generated measurable impact beyond its "
    "originating institution."
)

# Contribution 1: REALMS
add_evidence_block(
    title="REALMS — Registered Software Platform (INPI BR512023001278-5)",
    fields=[
        ("Related Criterion(s)", "Criterion 5 — Original Contributions of Major Significance"),
        ("Institution/Entity", "IP.TV LAB EDUCATION LTDA / Instituto Nacional da Propriedade Industrial (INPI)"),
        ("Type of Evidence", "Software Registration Certificate (INPI)"),
        ("Date Issued", "16 May 2023 (Registration Approval) / 10 August 2022 (Publication)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.gov.br/inpi"),
    ],
    description=[
        "REALMS is a proprietary educational technology platform developed under Mr. De Lello's "
        "engineering leadership at IP.TV LAB EDUCATION LTDA. Registered with INPI under certificate "
        "number BR512023001278-5, the platform was developed by a team of eleven co-authors and "
        "employs a multi-language technical architecture (C, C++, Java, JavaScript, Swift) spanning "
        "application software, commercial distribution, graphics/imaging, and operating system "
        "integration layers.",

        "The platform's applications encompass Education (ED-04), Communications (CO-04), and "
        "Technology (TC-02) domains, as classified by INPI's taxonomy. REALMS has been deployed in "
        "major government education initiatives, providing interactive learning environments designed "
        "for high-capacity, multi-user deployments. Its registration validity extends for 50 years "
        "from January 1, 2023, reflecting its enduring technical and commercial significance.",
    ],
    institutional_box=(
        "The Instituto Nacional da Propriedade Industrial (INPI) is the Brazilian federal agency "
        "responsible for the registration and protection of intellectual property, including "
        "software, patents, trademarks, and industrial designs. Established in 1970 and linked to "
        "the Ministry of Development, Industry and Trade, INPI serves as Brazil's official "
        "intellectual property office and is a member of the World Intellectual Property "
        "Organization (WIPO)."
    )
)

# Contribution 2: Mano (Android)
add_evidence_block(
    title="Mano (Android) — Mobile Assistive Technology Application (INPI BR512018051989-0)",
    fields=[
        ("Related Criterion(s)", "Criterion 5 — Original Contributions of Major Significance"),
        ("Institution/Entity", "IP.TV LTDA / Instituto Nacional da Propriedade Industrial (INPI)"),
        ("Type of Evidence", "Software Registration Certificate (INPI)"),
        ("Date Issued", "06 November 2018 (Registration Approval) / 07 October 2018 (Publication)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.gov.br/inpi"),
    ],
    description=[
        "Mano is a mobile application leveraging neural network approaches for hand gesture "
        "recognition, developed under Mr. De Lello's technical leadership at IP.TV LTDA. Registered "
        "with INPI under certificate number BR512018051989-0, the application was created by a team "
        "of seven co-authors using C++ and Java, with classification spanning Education (ED-04), "
        "Communications (CO-04), and Technology (TC-02) domains.",

        "The Mano application represents a direct commercial translation of Mr. De Lello's academic "
        "research in surface electromyography (sEMG)-based gesture recognition systems into an "
        "accessible mobile platform. By applying neural network architectures to real-time gesture "
        "interpretation, the application addresses critical accessibility challenges in assistive "
        "technology and rehabilitation contexts. Its registration validity extends for 50 years from "
        "January 1, 2019.",
    ]
)

# Contribution 3: SynCast IP.TV Sync
add_evidence_block(
    title="SynCast IP.TV Sync — Enterprise Broadcast Synchronization Platform (INPI Registered)",
    fields=[
        ("Related Criterion(s)", "Criterion 5 — Original Contributions of Major Significance"),
        ("Institution/Entity", "VAT Tecnologia / Instituto Nacional da Propriedade Industrial (INPI)"),
        ("Type of Evidence", "Software Registration Certificate (INPI)"),
        ("Date Issued", "15 October 2014"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.gov.br/inpi"),
    ],
    description=[
        "SynCast IP.TV Sync is an enterprise-grade broadcast and streaming synchronization platform "
        "developed under Mr. De Lello's technical direction at VAT Tecnologia. The platform was "
        "designed for large-scale corporate deployments requiring real-time synchronization of "
        "broadcast content across distributed network infrastructure.",

        "The platform was commercially deployed by Embratel, one of Brazil's largest "
        "telecommunications companies, for the Boticario retail chain project, demonstrating its "
        "viability for enterprise-scale operations. The dual-category recognition at the 2013 "
        "Assespro-RJ awards (Best Telecommunications Solution and Best IT Infrastructure Solution) "
        "further validated SynCast's technical excellence and market significance.",
    ]
)

# Contribution 4: sEMG Research
add_evidence_block(
    title="Novel sEMG-Based Hand Gesture Classification Methodology (95.2% Accuracy)",
    fields=[
        ("Related Criterion(s)", "Criterion 5 — Original Contributions of Major Significance"),
        ("Institution/Entity", "PEE/COPPE, Universidade Federal do Rio de Janeiro (UFRJ)"),
        ("Type of Evidence", "Peer-Reviewed Research Publication / Master's Thesis"),
        ("Date Issued", "2024 (Journal Publication) / 21 August 2025 (Degree Conferred)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.coppe.ufrj.br"),
    ],
    description=[
        "Mr. De Lello developed and validated a novel feature extraction and classification "
        "methodology for surface electromyography (sEMG)-based hand gesture recognition, achieving "
        "95.2% accuracy in six-gesture classification tasks. This research, published in Learning "
        "and Nonlinear Models (the journal of the Brazilian Society on Computational Intelligence), "
        "systematically compared multiple classification algorithms applied to sEMG signals, "
        "establishing a new benchmark for the field.",

        "The significance of this contribution lies in its direct applicability to prosthetic device "
        "control and upper-limb rehabilitation technologies. By providing an open-source, "
        "reproducible methodology validated against public datasets, Mr. De Lello's research "
        "enables other researchers and engineers to build upon his findings, accelerating the "
        "development of affordable assistive technologies for individuals with upper-limb "
        "impairments. The research was conducted under the supervision of Prof. Markus Vinicius "
        "Santos Lima at COPPE/UFRJ, Brazil's most prestigious graduate engineering program.",
    ],
    institutional_box=(
        "COPPE (Instituto Alberto Luiz Coimbra de Pos-Graduacao e Pesquisa de Engenharia) at "
        "Universidade Federal do Rio de Janeiro (UFRJ) is the largest engineering research and "
        "graduate education center in Latin America. Founded in 1963, COPPE operates 13 graduate "
        "programs and is consistently ranked among the top engineering institutions in the Southern "
        "Hemisphere, with research output published in leading international journals and conference "
        "proceedings."
    )
)

# Contribution 5: NILM Research
add_evidence_block(
    title="Weightless Neural Network Architecture for Nonintrusive Load Monitoring (NILM)",
    fields=[
        ("Related Criterion(s)", "Criterion 5 — Original Contributions of Major Significance"),
        ("Institution/Entity", "PEE/COPPE and PESC/COPPE, Universidade Federal do Rio de Janeiro (UFRJ)"),
        ("Type of Evidence", "IEEE Conference Publication"),
        ("Date Issued", "May 2020 (IEEE IPDPSW 2020)"),
        ("Location", "New Orleans, Louisiana, United States"),
        ("Website/URL", "https://ieeexplore.ieee.org"),
    ],
    description=[
        "Mr. De Lello co-authored a novel approach to energy consumption monitoring using the "
        "WiSARD (Wilkes, Stonham, and Aleksander Recognition Device) weightless neural network "
        "architecture applied to Nonintrusive Load Monitoring (NILM). Published in the proceedings "
        "of the 2020 IEEE International Parallel and Distributed Processing Symposium Workshops "
        "(IPDPSW), this research presented a computationally efficient method for disaggregating "
        "aggregate electrical consumption data into individual appliance-level profiles without "
        "requiring dedicated monitoring hardware.",

        "NILM technology holds critical importance for energy efficiency and sustainability "
        "initiatives, enabling building managers and utility companies to identify energy waste "
        "and optimize consumption patterns. By applying weightless neural networks, a class of "
        "machine learning architecture developed at UFRJ, Mr. De Lello's research demonstrated "
        "that accurate load disaggregation can be achieved with significantly reduced computational "
        "overhead compared to conventional deep learning approaches, facilitating deployment on "
        "resource-constrained IoT devices.",
    ],
    institutional_box=(
        "The IEEE (Institute of Electrical and Electronics Engineers) is the world's largest "
        "technical professional organization, with over 400,000 members in more than 160 countries. "
        "The International Parallel and Distributed Processing Symposium (IPDPS) is a premier "
        "international forum for presenting research results in parallel processing, distributed "
        "computing, and related areas. IEEE publications are indexed in Scopus, Web of Science, and "
        "other major academic databases."
    )
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 5 — C6: AUTHORSHIP OF SCHOLARLY ARTICLES
# ═══════════════════════════════════════════════════════════════

add_section_title("AUTHORSHIP OF SCHOLARLY ARTICLES IN THE FIELD")

add_body(
    "Mr. De Lello has authored peer-reviewed scholarly articles published in indexed "
    "international venues, including IEEE conference proceedings and the journal of the "
    "Brazilian Society on Computational Intelligence. These publications address advanced "
    "topics in machine learning, signal processing, and neural network architectures with "
    "direct applications in assistive technology and energy efficiency."
)

# Article 1
add_evidence_block(
    title="\"Comparison of sEMG-Based Hand Gesture Classifiers\" — Learning and Nonlinear Models (SBIC), 2024",
    fields=[
        ("Related Criterion(s)", "Criterion 6 — Authorship of Scholarly Articles"),
        ("Institution/Entity", "Brazilian Society on Computational Intelligence (SBIC) / PEE/COPPE, UFRJ"),
        ("Type of Evidence", "Peer-Reviewed Journal Article"),
        ("Date Issued", "2024 (Volume 22, Issue 2, Pages 48-61)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://sbic.org.br"),
    ],
    description=[
        "This article presents a systematic comparative assessment of multiple hand gesture "
        "recognition algorithms applied to surface electromyography (sEMG) data. Co-authored with "
        "Gabriel S. Chaves, Juliano F. Caldeira, and Prof. Markus V. S. Lima, the study evaluated "
        "feature extraction and classification methodologies using a public dataset, achieving a "
        "peak classification accuracy of 95.2% in six-gesture recognition tasks.",

        "The article was published in Learning and Nonlinear Models, the official journal of the "
        "Brazilian Society on Computational Intelligence (SBIC), a peer-reviewed, indexed "
        "publication dedicated to advancing research in machine learning, neural networks, and "
        "computational intelligence. The study's use of open-source code and reproducible "
        "methodology represents a significant contribution to the accessibility and advancement of "
        "assistive technology research.",
    ],
    institutional_box=(
        "The Brazilian Society on Computational Intelligence (SBIC, Sociedade Brasileira de "
        "Inteligencia Computacional) is a scientific organization affiliated with the IEEE "
        "Computational Intelligence Society. Its journal, Learning and Nonlinear Models, publishes "
        "original research in machine learning, neural networks, fuzzy systems, and evolutionary "
        "computation, and is indexed in national and international academic databases."
    )
)

# Article 2
add_evidence_block(
    title="\"Weightless Neural Networks Applied to Nonintrusive Load Monitoring\" — IEEE IPDPSW, 2020",
    fields=[
        ("Related Criterion(s)", "Criterion 6 — Authorship of Scholarly Articles"),
        ("Institution/Entity", "IEEE / PEE and PESC, COPPE/UFRJ"),
        ("Type of Evidence", "Conference Proceedings Article (Peer-Reviewed)"),
        ("Date Issued", "May 2020"),
        ("Location", "New Orleans, Louisiana, United States"),
        ("Website/URL", "https://ieeexplore.ieee.org"),
    ],
    description=[
        "Co-authored with Juliano F. Caldeira, Mauricio Aredes, Felipe M. G. Franca, and Priscila "
        "M. V. Lima, this article was published in the proceedings of the 2020 IEEE International "
        "Parallel and Distributed Processing Symposium Workshops (IPDPSW). The paper presents the "
        "application of the WiSARD weightless neural network to Nonintrusive Load Monitoring "
        "(NILM), a critical technology for energy efficiency and smart grid infrastructure.",

        "The article was accepted through IEEE's rigorous peer-review process and presented at one "
        "of the premier international forums for parallel and distributed processing research. "
        "Registration confirmation (Invoice 1320-0237-0244, April 30, 2020) documents Mr. De "
        "Lello's author registration for the conference. The publication is indexed in IEEE Xplore, "
        "Scopus, and Web of Science.",
    ]
)

# Article 3
add_evidence_block(
    title="Master's Dissertation: \"A Comparative Study of Classifiers for sEMG-Based Hand Gesture Recognition Systems\" — UFRJ, 2025",
    fields=[
        ("Related Criterion(s)", "Criterion 6 — Authorship of Scholarly Articles"),
        ("Institution/Entity", "Programa de Engenharia Eletrica (PEE/COPPE), Universidade Federal do Rio de Janeiro"),
        ("Type of Evidence", "Master's Dissertation / Academic Publication"),
        ("Date Issued", "21 August 2025 (Degree Conferred) / 21 March 2025 (Defense)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.pee.ufrj.br"),
    ],
    description=[
        "Mr. De Lello's Master's dissertation presents a comprehensive comparative analysis of "
        "multiple classification algorithms for prosthetic control applications using sEMG signals. "
        "Defended on March 21, 2025, under the supervision of Prof. Markus Vinicius Santos Lima, "
        "the dissertation consolidates and extends the research published in the SBIC journal, "
        "providing additional experimental validation and theoretical framework.",

        "The dissertation was evaluated by a committee of professors at COPPE/UFRJ, the largest "
        "and most prestigious graduate engineering research center in Latin America. The degree was "
        "officially conferred on August 21, 2025, as documented by the official diploma (Serie A, "
        "No. 047657) issued by Universidade Federal do Rio de Janeiro.",
    ]
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 6 — C8: LEADING OR CRITICAL ROLE
# ═══════════════════════════════════════════════════════════════

add_section_title("LEADING OR CRITICAL ROLE IN DISTINGUISHED ORGANIZATIONS")

add_body(
    "Mr. De Lello has performed in leading and critical roles within distinguished organizations "
    "whose operations span technology development, educational infrastructure deployment, and "
    "enterprise solutions at national and international scale. His leadership is documented "
    "through corporate formation records, government project documentation, and independently "
    "verified commercial outcomes."
)

# Role 1: IP.TV
add_evidence_block(
    title="Founder and Principal Engineering Strategist — IP.TV LTDA / IP.TV LAB EDUCATION LTDA",
    fields=[
        ("Related Criterion(s)", "Criterion 8 — Leading or Critical Role"),
        ("Institution/Entity", "IP.TV LTDA and IP.TV LAB EDUCATION LTDA"),
        ("Type of Evidence", "Corporate Registration / Partnership Records / Project Documentation"),
        ("Date Issued", "[VERIFICAR — Company Formation Date]"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "[VERIFICAR]"),
    ],
    description=[
        "As founder and co-founder of IP.TV LTDA and IP.TV LAB EDUCATION LTDA, Mr. De Lello serves "
        "as the principal engineering strategist responsible for the conception, technical "
        "architecture, and delivery of the company's entire product portfolio. His leadership "
        "encompasses the direction of complex technical teams, management of government-scale "
        "contracts, and strategic decision-making regarding technology selection and system "
        "architecture.",

        "Under Mr. De Lello's engineering leadership, IP.TV has developed and deployed multiple "
        "proprietary software platforms (REALMS, Mano, EduxGen.AI) serving educational institutions "
        "and government clients. The company's most significant achievement is the Centro de Midias "
        "SP (CMSP), a platform that delivered simultaneous educational access to over one million "
        "students and educators for the State of Sao Paulo during the COVID-19 pandemic. This "
        "deployment represents one of the largest emergency educational technology initiatives in "
        "Latin American history and was recognized by the Inter-American Development Bank with the "
        "Gobernarte 2020 Award.",

        "Mr. De Lello's role in the organization is not limited to technical oversight. His "
        "responsibilities include high-level project management, strategic technology direction, "
        "client relationship management with government agencies, and the leadership of a "
        "multi-disciplinary engineering team responsible for platform development, deployment, and "
        "maintenance at scale.",
    ]
)

# Role 2: CMSP Project
add_evidence_block(
    title="Technical Project Director — Centro de Midias SP (CMSP) Platform for SEDUC-SP",
    fields=[
        ("Related Criterion(s)", "Criterion 8 — Leading or Critical Role"),
        ("Institution/Entity", "Secretaria de Educacao do Estado de Sao Paulo (SEDUC-SP) / IP.TV LTDA"),
        ("Type of Evidence", "Government Project Documentation / Functional Specifications / Donation Terms"),
        ("Date Issued", "March-April 2020 (Platform Deployment)"),
        ("Location", "Sao Paulo, SP, Brazil"),
        ("Website/URL", "[VERIFICAR]"),
    ],
    description=[
        "The Centro de Midias SP (CMSP) is a state-level educational technology platform "
        "commissioned by the Secretariat of Education of the State of Sao Paulo (SEDUC-SP) to "
        "ensure continuity of public education during the COVID-19 pandemic. Mr. De Lello served "
        "as the technical project director responsible for the platform's architecture, development, "
        "and deployment.",

        "The project's documentation includes functional specifications dated March 23, 2020; "
        "application authorization dated March 25, 2020; donation terms dated April 7, 2020; and "
        "government tender documentation dated April 1, 2020. These records demonstrate the "
        "extraordinary pace of deployment, with a fully operational platform serving over one "
        "million simultaneous users delivered within weeks of project initiation.",

        "The platform's infrastructure encompasses live streaming, videoconferencing, content "
        "management, and interactive learning capabilities integrated into a unified system "
        "accessible across mobile and desktop devices. Mr. De Lello's critical role in designing "
        "and delivering this infrastructure under extreme time pressure and at unprecedented scale "
        "is evidenced by the project documentation and the subsequent IDB Gobernarte recognition.",
    ],
    institutional_box=(
        "The Secretaria de Educacao do Estado de Sao Paulo (SEDUC-SP) is the education authority "
        "of the State of Sao Paulo, the most populous state in Brazil with approximately 46 million "
        "inhabitants. SEDUC-SP oversees the largest public education network in Latin America, "
        "serving millions of students across thousands of schools. The Centro de Midias SP platform "
        "was a critical component of the state's emergency response to the COVID-19 pandemic."
    )
)

# Role 3: VAT Tecnologia
add_evidence_block(
    title="Engineering Leadership — VAT Tecnologia / Logica Tecnologia",
    fields=[
        ("Related Criterion(s)", "Criterion 8 — Leading or Critical Role"),
        ("Institution/Entity", "VAT Tecnologia / Logica Tecnologia"),
        ("Type of Evidence", "Corporate Records / Award Documentation / Commercial Contracts"),
        ("Date Issued", "[VERIFICAR — Period of Employment]"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "[VERIFICAR]"),
    ],
    description=[
        "Mr. De Lello held a leading engineering role at VAT Tecnologia (subsequently known as "
        "Logica Tecnologia), where he directed the technical development of the SynCast IP.TV Sync "
        "platform. His leadership in this position is evidenced by the platform's commercial "
        "deployment with Embratel (one of Brazil's major telecommunications companies) for the "
        "Boticario retail chain project, and by the dual-category recognition at the 2013 "
        "Assespro-RJ Best Companies Award.",

        "Documentation includes Embratel project requests (2011), technical and commercial proposals, "
        "and project kickoff and pilot testing records (2012), collectively demonstrating "
        "Mr. De Lello's critical role in bringing the SynCast platform from concept through "
        "development to commercial deployment with a major telecommunications partner.",
    ]
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 7 — INTELLECTUAL PROPERTY
# ═══════════════════════════════════════════════════════════════

add_section_title("INTELLECTUAL PROPERTY AND INDUSTRIAL REGISTRATIONS")

add_body(
    "Mr. De Lello holds registered intellectual property rights on four software programs "
    "registered with the Instituto Nacional da Propriedade Industrial (INPI), Brazil's "
    "official intellectual property office. Each registration reflects a distinct original "
    "contribution to the fields of educational technology, assistive technology, and "
    "enterprise broadcast systems."
)

# IP Table
ip_table = doc.add_table(rows=5, cols=5)
ip_table.alignment = WD_TABLE_ALIGNMENT.CENTER

# Headers
headers = ["Software Name", "INPI Registration", "Publication Date", "Validity", "Application Domains"]
for i, h in enumerate(headers):
    cell = ip_table.cell(0, i)
    p = cell.paragraphs[0]
    run = p.add_run(h)
    set_font(run, size=10, bold=True)
    # Header background
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{HEADER_BG}" w:val="clear"/>')
    tcPr.append(shd)

# Data rows
ip_data = [
    ["REALMS", "BR512023001278-5", "10 August 2022", "50 years (from 01/01/2023)", "Education, Communications, Technology"],
    ["Mano (Android)", "BR512018051989-0", "07 October 2018", "50 years (from 01/01/2019)", "Education, Communications, Technology"],
    ["Mano (iOS)", "[VERIFICAR]", "[VERIFICAR]", "[VERIFICAR]", "Education, Communications, Technology"],
    ["SynCast IP.TV Sync", "[VERIFICAR]", "15 October 2014", "[VERIFICAR]", "Telecommunications, IT Infrastructure"],
]
for row_idx, row_data in enumerate(ip_data):
    for col_idx, val in enumerate(row_data):
        cell = ip_table.cell(row_idx + 1, col_idx)
        p = cell.paragraphs[0]
        run = p.add_run(val)
        set_font(run, size=10)

# Table borders
tbl2 = ip_table._tbl
tblPr2 = tbl2.tblPr if tbl2.tblPr is not None else parse_xml(f'<w:tblPr {nsdecls("w")}/>')
borders2 = parse_xml(
    f'<w:tblBorders {nsdecls("w")}>'
    f'<w:top w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'<w:left w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'<w:bottom w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'<w:right w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'<w:insideH w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'<w:insideV w:val="single" w:sz="4" w:space="0" w:color="{BORDER_COLOR}"/>'
    f'</w:tblBorders>'
)
existing_b = tblPr2.find(qn('w:tblBorders'))
if existing_b is not None:
    tblPr2.remove(existing_b)
tblPr2.append(borders2)

doc.add_paragraph()  # spacing

# ═══════════════════════════════════════════════════════════════
# BLOCO 8 — ACADEMIC BACKGROUND
# ═══════════════════════════════════════════════════════════════

add_section_title("ACADEMIC BACKGROUND AND PROFESSIONAL EDUCATION")

# Master's
add_evidence_block(
    title="Master of Science in Electrical Engineering — Universidade Federal do Rio de Janeiro (UFRJ)",
    fields=[
        ("Institution/Entity", "Programa de Engenharia Eletrica (PEE/COPPE), Universidade Federal do Rio de Janeiro"),
        ("Type of Evidence", "Official Diploma (Serie A, No. 047657)"),
        ("Date Issued", "21 August 2025 (Degree Conferred) / 21 March 2025 (Defense)"),
        ("Period", "[VERIFICAR — Start Year] to August 2025"),
        ("Title/Distinction Awarded", "Mestre em Engenharia Eletrica (Master in Electrical Engineering)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.pee.ufrj.br"),
    ],
    description=[
        "Mr. De Lello completed his Master of Science degree in Electrical Engineering at "
        "COPPE/UFRJ, the largest graduate engineering research center in Latin America. His "
        "research focused on sEMG-Based Hand Gesture Recognition Systems, conducted under the "
        "supervision of Prof. Markus Vinicius Santos Lima within the Signal Processing Laboratory.",

        "The program encompassed advanced coursework in machine learning, signal processing, "
        "statistical learning theory, and neural network architectures, complemented by original "
        "research resulting in peer-reviewed publications in IEEE proceedings and the SBIC journal. "
        "The dissertation, titled \"A Comparative Study of Classifiers for sEMG-Based Hand Gesture "
        "Recognition Systems,\" was successfully defended on March 21, 2025, before a committee of "
        "COPPE faculty members.",
    ],
    institutional_box=(
        "Universidade Federal do Rio de Janeiro (UFRJ), founded in 1920, is consistently ranked "
        "among the top universities in Latin America and is the largest federal university in "
        "Brazil. COPPE/UFRJ, its graduate engineering institute, operates 13 graduate programs and "
        "is recognized as the most prestigious engineering research center in the Southern "
        "Hemisphere, with alumni and faculty contributing to major technological advancements in "
        "Brazil and internationally."
    )
)

# Bachelor's
add_evidence_block(
    title="Bachelor of Engineering in Electronic and Computing Engineering — Universidade Federal do Rio de Janeiro (UFRJ)",
    fields=[
        ("Institution/Entity", "Escola Politecnica, Universidade Federal do Rio de Janeiro"),
        ("Type of Evidence", "Official Diploma (Serie D, No. 069009)"),
        ("Date Issued", "14 June 2010"),
        ("Period", "[VERIFICAR — Start Year] to June 2010"),
        ("Title/Distinction Awarded", "Engenheiro Eletronico e de Computacao (Electronic and Computing Engineer)"),
        ("Location", "Rio de Janeiro, RJ, Brazil"),
        ("Website/URL", "https://www.poli.ufrj.br"),
    ],
    description=[
        "Mr. De Lello earned his Bachelor of Engineering degree in Electronic and Computing "
        "Engineering from the Escola Politecnica of Universidade Federal do Rio de Janeiro (UFRJ). "
        "The program provided a comprehensive foundation in electronics, computational engineering, "
        "digital systems design, signal processing, and control systems.",

        "The Escola Politecnica of UFRJ is one of the most selective engineering schools in Brazil, "
        "admitting students through a highly competitive national entrance examination. The "
        "Electronic and Computing Engineering program covers core areas including circuit theory, "
        "electromagnetic theory, semiconductor physics, computer architecture, algorithm design, "
        "and systems engineering, providing the technical foundation upon which Mr. De Lello has "
        "built his career in engineering management and technology innovation.",
    ]
)

# ═══════════════════════════════════════════════════════════════
# BLOCO 9 — ADDENDUM
# ═══════════════════════════════════════════════════════════════

add_section_title("ADDENDUM: IMPACT NARRATIVE AND STRATEGIC EVIDENCE")

add_body(
    "Guilherme Caldeira De Lello's professional trajectory represents a sustained arc of "
    "extraordinary achievement spanning sixteen years, from his graduation in Electronic and "
    "Computing Engineering at UFRJ in 2010 through his completion of a Master of Science in "
    "Electrical Engineering at COPPE/UFRJ in 2025. This arc is characterized by a rare and "
    "productive convergence of deep technical expertise with executive-level engineering "
    "management capacity, resulting in measurable impact across multiple dimensions of the "
    "field."
)

add_body(
    "In the domain of technology enterprise leadership, Mr. De Lello founded and directed "
    "organizations that have delivered infrastructure-critical technology platforms at national "
    "scale. The Centro de Midias SP platform, serving over one million simultaneous users for "
    "the State of Sao Paulo's education system, stands as one of the most significant emergency "
    "educational technology deployments in Latin American history. This achievement was "
    "independently validated by the Inter-American Development Bank through the Gobernarte 2020 "
    "Award, selected from 127 initiatives across 12 nations."
)

add_body(
    "In the domain of applied research and original contributions, Mr. De Lello has produced "
    "peer-reviewed publications in IEEE proceedings and the Brazilian Society on Computational "
    "Intelligence journal, advancing the fields of sEMG-based hand gesture recognition for "
    "prosthetic devices and weightless neural networks for energy monitoring. His four INPI-"
    "registered software programs translate these research innovations into commercially "
    "deployed products serving educational institutions, assistive technology users, and "
    "enterprise clients."
)

add_body(
    "In the domain of international recognition, Mr. De Lello has received four independent "
    "awards from organizations spanning three continents: the Inter-American Development Bank "
    "(Washington, D.C.), Tech & Learning Magazine (United States), the Qatar Foundation (Doha), "
    "and Assespro-RJ (Brazil). These recognitions span a fifteen-year period (2009-2024), "
    "confirming the sustained and evolving nature of his contributions to the field."
)

add_body(
    "Mr. De Lello's proposed endeavor in the United States centers on strategic engineering "
    "management in infrastructure-critical technology sectors, including AI-powered educational "
    "platforms, advanced automation systems, and renewable energy technology. These sectors align "
    "with national priorities articulated in Executive Order 14277 (Advancing Artificial "
    "Intelligence Education for American Youth, April 2025) and Executive Order 14278 (Preparing "
    "Americans for High-Paying Skilled Trade Jobs of the Future, April 2025), as well as the "
    "broader federal strategic framework for STEM workforce development. The U.S. Bureau of "
    "Labor Statistics (May 2024) reports that Architectural and Engineering Managers (SOC 11-9041) "
    "represent a high-demand occupation with a national annual median wage of $165,370, reflecting "
    "the critical need for professionals with Mr. De Lello's demonstrated combination of technical "
    "depth and management excellence."
)

# ─── SAVE ──────────────────────────────────────────────────────
doc.save(OUTPUT_FILE)
print(f"Document saved to: {OUTPUT_FILE}")
print(f"File size: {os.path.getsize(OUTPUT_FILE):,} bytes")
